---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \definecolor{shadecolor}{RGB}{242,242,242}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
---


```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(odb("name", "analysis"))
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

- `r odk("herb")` 绘制活性成分-靶点图。
    - 结果见 Fig. \@ref(fig:BaiMaoGen-network-pharmacology-visualization)

- 靶点与IgA肾病差异基因Venn图。
    - 结果见 Fig. \@ref(fig:intersection-venn-plot)

# 材料和方法 {#methods}

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## `r odb("herb", "analysis")`

### 成分

```{r}
hb <- job_herb("白茅根")
sig(hb) <- "BaiMaoGen"
hb@params$herbs_info %<>% slice(1)
hb <- step1(hb)
hb <- step2(hb, 100)
hb@step <- 2L
hb <- step3(hb)
clear(hb)

hb@plots$step3$p.pharm
```

```{r eval = T, echo = F, results = "asis"}
#| Herbs-information
autor(hb@params$herbs_info)
```

```{r eval = T, echo = F, results = "asis"}
#| Components-of-Herbs
autor(hb@tables$step1$herbs_compounds, key = "Ingredient.name")
```

```{r eval = T, echo = F, results = "asis"}
#| intersection-of-all-compounds
# autor(wrap(hb@plots$step3$p.herbs_compounds, 12))
```

### 成分靶点

```{r eval = T, echo = F, results = "asis"}
#| tables-of-Herbs-compounds-and-targets
autor(hb@params$easyRead)
```

```{r eval = T, echo = F, results = "asis"}
#| BaiMaoGen-network-pharmacology-visualization
autor(hb@plots$step3$p.pharm)
```

## IgA 肾炎 (IgA Nephropathy) 差异基因

```{r eval = T, echo = F, results = "asis"}
#| metadata-of-used-samples
autor(as_tibble(lm@params$normed_data$targets), key = "group")
```

```{r eval = T, echo = F, results = "asis"}
#| tables-of-DEGs
autor(lm@tables$step2$tops[[1]])
```

```{r}
geo2 <- job_geo("GSE175759")
geo2 <- step1(geo2)
file.copy("../2023_10_23_fanghejing/GSE175759", ".", recursive = T)
```

```{r}
metadata <- dplyr::filter(geo2@params$guess, diagnosis.ch1 %in% c("Control", "IgAN"), technical.outlier.ch1 == "No")
metadata <- dplyr::rename(metadata, sample = rownames, group = diagnosis.ch1)

fun <- function() {
  files <- list.files("./GSE175759/", "GSM.*", full.names = T)
  names(files) <- gs(get_realname(files), "(GSM[0-9]+).*", "\\1")
  files <- files[ names(files) %in% metadata$sample ]
  lst <- sapply(files, ftibble, simplify = F)
  lst <- lapply(lst, dplyr::rename, value = 2)
  data <- data.table::rbindlist(lst, idcol = T)
  data <- tidyr::spread(data, .id, value)
  as_tibble(data)
}
counts <- dplyr::mutate(fun(), id = gs(id, "\\.[0-9]*$", ""))

mart <- getOption("biomart")[[1]]
genes <- filter_biomart(mart, general_attrs(), "ensembl_gene_id", counts$id)
genes <- dplyr::relocate(genes, ensembl_gene_id, hgnc_symbol)
```

```{r}
lm <- job_limma(new_dge(metadata, counts, genes))
lm <- step1(lm)
lm <- step2(lm, IgAN - Control, use = "adj")
lm@plots$step2$p.valcano[[1]]
```

```{r}
save.image()
```

## `r odb("herb")` 靶点和 IgA 肾病差异基因的交集

去除缺失数据后，交集为：

```{r eval = T, echo = F, results = "asis"}
#| intersection-venn-plot
autor(p.venn)
```

```{r eval = T, echo = F, results = "asis"}
#| inter-gene
autor(lich)
```

```{r}
p.venn <- new_venn(DEGs = lm@tables$step2$tops[[1]]$hgnc_symbol, Herb_target = hb@params$easyRead$Target.name)
lich <- new_lich(list(intersection = attributes(p.venn)[[ "ins" ]]))
```

