---
---

```{r include = F, eval = F}
info <- items(start = td("2023-09-13"), end = td("2025-02-28"), finish = td(NA),
  id = "BSZD230913", client = "朱彤", inst = "",
  type = "生信分析",
  title = "相分离",
  save = ".items_analysis.rds"
)
show.ic(info)

order_publish.bosai("analysis.Rmd", "analysis_out.Rmd")
idname <- formatName.bosai("./analysis_out.docx")
order_packaging("./analysis_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("相分离")
)

```

```{r}
#| route
route <- as_network(
  list("Phase_separation:DB_PhaSepDB",
    ":, ",
    ), "sugiyama"
)
p.route <- flowChart(route, 1.1, 1)
p.route
```

```{r eval = T, echo = F, results = "asis"}
#| Route
autor(p.route)
```


# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

## PhaSepDB 相分离相关蛋白 (LLPS)

`r snap(ps.llps, 0:1)`

```{r}
ps.llps <- job_ps()
ps.llps <- step1(ps.llps)
#' @meth {get_meth(ps.llps)}
ps.llps@params$p.location
ps.llps@params$p.org
feature(ps.llps)
```

# 总结 {#conclusion}

