---
---

```{r include = F, eval = F}
info <- items(start = td("2025-02-18"), end = td("2025-02-24"), finish = td("2025-02-20"),
  id = "BSCL250212", client = "董林", inst = "",
  type = "思路设计",
  title = "结肠癌CALM3",
  save = ".items_idea.rds"
)
show.ic(info)

order_publish.bosai("idea.Rmd", "idea_out.Rmd")
formatName.bosai("./idea_out.docx")
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"), autor_asis = F)
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 研究背景 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("骨髓瘤")
)

```

分析 CALM3 在结肠癌中的表达和功效。

## 思路 {#introduction}

```{r}
#| route
route <- as_network(
  list("结肠癌:TCGA, GTEx, GEO",
    "TCGA, GTEx:Cancer_vs_Normal:DEGs:CALM3, Others:STRINGdb_PPI, 关联分析:富集分析",
    "TCGA:CALM3生存分析, 突变数据分析",
    "突变数据分析:CALM3_SNP",
    "GEO:scRNA-seq:细胞聚类:细胞注释:各细胞CALM3表达:CALM3拟时分析"
    ), "sugiyama"
)
p.route <- flowChart(route, 1.1, 1)
p.route
```

```{r eval = T, echo = F, results = "asis"}
#| Route
autor(p.route)
```

