---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(3), eval = ic(0, 1, 1, 1, 0))
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

- 养阴通脑颗粒中治疗脑缺血再灌注的关键成分及相应信号通路（信号通路需要由创新性的），1-3条
- 同时重点分析水蛭素对应的治疗脑缺血再灌注的信号通路

养阴通脑颗粒：地黄15g、黄芪15g、葛根18g、石斛15g、水蛭3g、川芎9g

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
herbs <- c("地黄", "黄芪", "葛根", "石斛", "水蛭", "川芎")

hb <- job_herb(herbs)
hb@params$herbs_info %<>% dplyr::distinct(Herb_cn_name, .keep_all = T)
hb@params$herbs_info
hb <- step1(hb)
hb@tables$step1$herbs_compounds
hb <- step2(hb)

```
