---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
output:
  custom_docx_document2:
    reference_docx: '`r system.file("extdata", "bosai.docx", package = "utils.tool")`'
---


```{r include = F, eval = F}
info <- items(start = td("2025-04-08"), end = td("2025-04-30"), finish = td("2025-04-09"),
  id = "BSJF230109", client = "吴东蛟", inst = "",
  type = "生信协助",
  title = "图片修改",
  save = ".items_support.rds"
)
show.ic(info)

order_publish.bosai("support.Rmd", "support_out.Rmd")
idname <- formatName.bosai("./support_out.docx")
order_packaging("./support_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

`r ref("Unnamed-1")`
`r ref("Network")`
`r ref("GO-enrichment-coord-polar")`
`r ref("KEGG-enrichment")`
`r ref("Network")`
<!-- LEGEND_END -->

```{r}
data_go <- ftibble("./order_material/BSJF230109-╬т╢лЄ╘-═°╥й╜с╣√-═°┬ч╥й└э╤з╝░╖╓╫╙╢╘╜╙╖╓╬Ў╠╜╛┐╕┤╖╜╧─╠ь╬▐╤╙╗║└р╖ч╩к╣╪╜┌╤╫╝▓▓б╖в╒╣╡─╗·╓╞-2023-02-06/plot/enrichment/GO/GO.result_top15.csv")
data_kegg <- ftibble("./order_material/BSJF230109-╬т╢лЄ╘-═°╥й╜с╣√-═°┬ч╥й└э╤з╝░╖╓╫╙╢╘╜╙╖╓╬Ў╠╜╛┐╕┤╖╜╧─╠ь╬▐╤╙╗║└р╖ч╩к╣╪╜┌╤╫╝▓▓б╖в╒╣╡─╗·╓╞-2023-02-06/plot/enrichment/KEGG/KEGG.result_top15.csv")
data_net <- ftibble("./order_material/BSJF230109-╬т╢лЄ╘-═°╥й╜с╣√-═°┬ч╥й└э╤з╝░╖╓╫╙╢╘╜╙╖╓╬Ў╠╜╛┐╕┤╖╜╧─╠ь╬▐╤╙╗║└р╖ч╩к╣╪╜┌╤╫╝▓▓б╖в╒╣╡─╗·╓╞-2023-02-06/plot/enrichment/KEGG/kegg_net.csv")
```

```{r}
p.go <- plot_go_polor(data_go)
p.go
```

```{r}
p.kegg <- plot_kegg(
  data_kegg, maxShow = 15, use = "pvalue", order.by = "Description", 
  use.log = TRUE, theme = theme(text = element_text(size = 20))
)
wrap(p.kegg, 10, 7)
```

```{r}
data_net <- dplyr::filter(
  data_net, genes %in% c("RXRA", "PPARA", "PPARG")
)

nodes <- tidyr::pivot_longer(data_net, 1:2, names_to = "type", values_to = "name")
nodes <- dplyr::distinct(nodes, name, .keep_all = TRUE)
nodes <- dplyr::mutate(nodes, id = name, .before = 1)
nodes

edges <- dplyr::select(data_net, source = genes, target = pathways)
edges

ggraph <- tidygraph::tbl_graph(nodes, edges, directed = TRUE)
ggraph <- dplyr::mutate(ggraph,
  centrality = tidygraph::centrality_pagerank(
    damping = .1, weights = jitter(rep(1, nrow(edges)), 10)
  )
)
layout <- ggraph::create_layout(ggraph, "centrality", centrality = tibble::as_tibble(ggraph)$centrality)

RCy3::createNetworkFromDataFrames(nodes, edges, title = "My Network", collection = "Demo")
RCy3::layoutNetwork("force-directed")

RCy3::setNodeFontFaceDefault("SansSerif.bold")
RCy3::setNodeFontSizeDefault(15)

RCy3::setEdgeTargetArrowShapeDefault("ARROW")
RCy3::setEdgeTargetArrowColorDefault(col2hex("Grey60"))
RCy3::setEdgeLineWidthDefault(2)

RCy3::setNodeColorMapping(
  table.column = "type", 
  table.column.values = unique(nodes$type),
  mapping.type = "d",
  colors = c("#4DBBD5", "#EFC000")
)

RCy3::setNodePositionBypass(layout$id, unname(layout$x) * 3, unname(layout$y) * 3)
# set to default postions
RCy3::layoutNetwork("force-directed")
# unlock bypass
clearNodePropertyBypass(layout$id, "NODE_Y_LOCATION")
clearNodePropertyBypass(layout$id, "NODE_X_LOCATION")

RCy3::fitContent()
RCy3::exportImage("./material/network.svg", type = "svg")
rsvg::rsvg_pdf("./material/network.svg", "./material/network.pdf")
p.network <- .file_fig("./material/network.pdf")
p.network
p.network <- set_lab_legend(
  p.network,
  glue::glue("network"),
  glue::glue("基因通路网络图。")
)
p.network
```



```{r eval = T, echo = F, results = "asis"}
#| GO-enrichment-coord-polar
autor(p.go)
```


```{r eval = T, echo = F, results = "asis"}
#| KEGG-enrichment
autor(wrap(p.kegg, 10, 7))
```


```{r eval = T, echo = F, results = "asis"}
#| Network
autor(p.network)
```

# 总结 {#conclusion}

