
# Project status

```{r}
summary_week.bosai(rm = T, must_include = "BSJF240734")
alls <- get_orders()
print(alls, n = Inf, width = 400)
```

## 2024-12-04

```{r}
alls <- dplyr::mutate(alls, cost = ifelse(type == "思路设计", 3, NA))
collate <- dplyr::select(alls, type, id, title, cost, finish)
collate <- dplyr::mutate(collate, name = paste0(id, ", ", title))
collate <- dplyr::select(collate, type, name, cost, finish)
collate <- dplyr::filter(collate, !is.na(finish))
data.table::fwrite(collate, "./summary/assess_data_1.csv")
browseURL("./summary/assess_data_1.csv")
```

## 2024-12-10

```{r}
alls <- get_orders()
alls
backup_jobs.bosai(alls, "2024-12-10")
```

## 2024-12-31


```{r}
orders <- get_orders()
month1 <- ftibble("./summary/assess_data_1.csv")
orders_month1 <- dplyr::filter(
  orders, id %in% strx(month1$name, "[^,]*"), finish <= max(month1$finish)
)
orders_month1 <- dplyr::mutate(orders_month1, summary_month = td("2024-12-04"), .before = 1)
orders_month1
saveRDS(orders_month1, "summary/records.rds")
saveRDS(orders_month1, "summary/month_records.rds")

summary_assess.bosai(get_orders())
```

## 2025-01-03

```{r}
summary_month.bosai(get_orders(), rm = TRUE)
```

## 2025-01-10

```{r}
alls <- get_orders()
backup_jobs.bosai(alls, "2025-01-10")

summary_week.bosai(rm = T)
```

## 2025-01-17

```{r}
summary_week.bosai(rm = T, must_include = "BSXG240327")
```

## 2025-02-05

```{r}
summary_assess.bosai(get_orders())

summary_month.bosai(get_orders(), rm = TRUE)
```

## 2025-02-08

```{r}
summary_week.bosai(rm = T)
```

## 2025-02-13

```{r}
alls <- get_orders()
backup_jobs.bosai(
  dplyr::filter(alls, finish <= td("2025-02-08")), "2025-02-13"
)
```

## 2025-02-14

```{r}
alls <- get_orders()
data <- dplyr::filter(alls, grpl(type, "生信|分析"), tags == "")

hasTags <- dplyr::filter(alls, tags != "")
hasTags <- dplyr::select(hasTags, id, title, tags.list)
hasTags <- dplyr::filter(hasTags, id != "_")
hasTags <- reframe_col(hasTags, "tags.list", unlist)
hasTags <- dplyr::mutate(
  hasTags, id_title = paste0(id, " (", title, ")"), .before = 1
)
hasTags <- dplyr::select(hasTags, -id, -title)
hasTags <- reframe_col(hasTags, "id_title", bind)
hasTags

extraTags <- tibble::tibble(tags.list = names(.tag_anno()))

allTags <- tbmerge(extraTags, hasTags, all.x = TRUE, by = "tags.list")
allTags <- dplyr::arrange(allTags, id_title)

allTags <- dplyr::mutate(allTags, Analysis = recode_tags(tags.list))
allTags <- dplyr::filter(allTags, !grpl(Analysis, "__dep__"))
allTags <- dplyr::select(allTags, Analysis, id_title)
allTags <- dplyr::mutate(
  allTags, Status = ifelse(
    is.na(id_title), "Not Finished", "Finished"
  ), .before = 1
)
allTags <- dplyr::mutate(
  allTags, Class = strx(Analysis, "(?<=\\[).*(?=\\])"), 
  Class = recode_tagClass(Class),
  .before = 1,
)
allTags <- dplyr::arrange(allTags, id_title, Class)
allTags

openxlsx::write.xlsx(allTags, "./summary/workflow_types.xlsx")
```

## 2025-02-14

```{r}
summary_week.bosai(rm = T, must_include = "BSGY240816")
```

## 2025-02-21

```{r}
summary_week.bosai(rm = T)
```

```{r}
# file <- "~/disk_sda1/backup/"
# data <- readRDS(file)
# data <- dplyr::filter(data, belong < td("2025-02-07"))
# saveRDS(data, file)
```

```{r}
file <- "~/outline/bosai/summary/month_records.rds"
data <- readRDS(file)

data <- dplyr::filter(data, belong < td("2025-02-07"))
saveRDS(data, file)

summary_month.bosai(get_orders(), rm = TRUE)
```

## 2025-02-28

```{r}
summary_month.bosai(
  get_orders(), rm = TRUE, must_include = "BSJF241107", upd = TRUE
)

```

# 2025-03-03

```{r}
# exclude: BSJF241107
all <- get_orders()
summary_assess.bosai(
  dplyr::filter(all, finish <= td("2025-03-03")), upd = TRUE
)
```

# 2025-03-07

```{r}
summary_week.bosai(rm = T, must_include = "BSXN240936")
```

# 2025-03-14

```{r}
summary_week.bosai(rm = TRUE)
```

# 2025-03-19

```{r}
alls <- get_orders()
alls
records <- readRDS("~/disk_sda1/backup/records.rds")
records <- dplyr::filter(records, finish < td("2025-02-08"))
saveRDS(records, "~/disk_sda1/backup/records.rds")

backup_jobs.bosai(
  dplyr::filter(alls, finish <= td("2025-03-03")), 
  "2025-03-13"
)
```

# 2025-03-21

```{r}
summary_week.bosai(rm = TRUE, must_include = "BSCL241113")
```

# 2025-03-28

```{r}
summary_month.bosai(get_orders(), rm = TRUE, upd = TRUE)
dplyr::filter(all, id == "BSJF241107")

summary_week.bosai(rm = TRUE)

# 2025-03-03
all <- get_orders()
summary_assess.bosai(all)
```

