---
---

```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover("title")
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

randomForestSRC

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
tc <- job_tcga("TCGA-LUAD")
not(tc)
tc <- step1(tc, query = c("mutation", "clinical"), F)
tc@tables$step1$cons
tc <- step2(tc)
tc <- step3(tc, query = "mutation")

```

```{r}
mf <- asjob_maf(tc)
mf@params$info.lich
mf <- step1(mf)
mf@plots$step1$p.summary
mf@plots$step1$p.oncoplot

x <- maftools::genesToBarcodes(mf@object, mf@object@gene.summary[[1]], justNames = T)

eg$res <- as.factor(letters[1:10])
obj <- randomForestSRC::rfsrc(res ~ ., data = eg, splitrule = 'gini')
imp <- randomForestSRC::vimp(obj)
```


