---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \definecolor{shadecolor}{RGB}{242,242,242}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
---


```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover("原始数据和图整理")
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

下载 TCGA 原始数据，绘制 Fig 1-3 内容。

## 数据统计

```{r eval = T, echo = F, results = "asis"}
#| data
autor(mf@params$info.lich)
```

## 原始数据

### 文件

```{r eval = T, echo = F, results = "asis"}
#| TCGA-LUAD-raw
autor("./GDCdata/TCGA-LUAD/Simple_Nucleotide_Variation/Masked_Somatic_Mutation/")
```

### 临床数据

```{r eval = T, echo = F, results = "asis"}
#| LUAD-clinical-data-filtered-by-vital-status
autor(mf@params$clinical, key = "bcr_followup_barcode")
```

## Figure 1-3

```{r eval = T, echo = F, results = "asis"}
#| LUAD-summary-of-mutation
autor(mf@plots$step1$p.summary)
```

```{r eval = T, echo = F, results = "asis"}
#| LUAD-oncoplot-of-top-genes
autor(mf@plots$step1$p.oncoplot)
```

```{r eval = T, echo = F, results = "asis"}
#| LUAD-Variable-importance
autor(rf@plots$step1$p.imp)
```

# 材料和方法 {#methods}

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

```{r}
tc <- job_tcga("TCGA-LUAD")
not(tc)
tc <- step1(tc, query = c("mutation", "clinical"), F)
tc@tables$step1$cons
tc <- step2(tc)
tc <- step3(tc, query = "mutation")

```

```{r}
mf <- asjob_maf(tc)
sig(mf) <- "LUAD"
mf@params$info.lich
mf <- step1(mf)
mf@plots$step1$p.summary
mf@plots$step1$p.oncoplot

rf <- asjob_rfsrc(mf)
sig(rf) <- "LUAD"

rf@step <- 0L
rf <- step1(rf)
rf@plots$step1$p.imp

rf@tables$step1$t.imp
```

```{r}
save.image()
```

