---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{tikz}
  \usepackage{auto-pst-pdf}
  \usepackage{pgfornament}
  \usepackage{pstricks-add}
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
info <- items(start = td("20231124"), end = td("20241108"), finish = td(""),
  id = "BSZD231122", client = "杨立宇", type = "分析优化", title = "骨肉瘤",
  save = ".items_opt.rds"
)
show.ic(info)

order_publish("opt.Rmd", "opt_out.Rmd")
file.rename("./opt_out.pdf", paste0(info$id, "分析优化.pdf"))
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"), autor_asis = F)
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("骨肉瘤")
)
# Osteosarcoma
```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```


# 分析结果 {#workflow}

```{r}
geo.os <- job_geo("GSE152048")
geo.os <- step1(geo.os)
geo.os@params$guess
# geo.os <- step2(geo.os)

lapply(unique(gs(geo.os@params$guess$title, " .*$", "")),
  function(x) {
    url <- glue::glue("https://ftp.ncbi.nlm.nih.gov/geo/series/GSE152nnn/GSE152048/suppl//GSE152048_{x}.matrix.tar.gz")
    cdRun("wget ", url, " -P ./GSE152048/")
  })

lapply(list.files("./GSE152048/", "tar.gz$"),
  function(file) {
    untar(file.path("GSE152048", file), exdir = "GSE152048")
  })
```

## Seurat 单细胞数据分析 (OS)

```{r}
sr.os <- job_seurat("./GSE152048/BC2")
sr.os <- step1(sr.os)
sr.os@plots$step1$p.qc

dirs <- list.files("./GSE152048", "^BC", full.names = T)
useWhich <- strx(dirs, "BC[0-9]+") %in% paste0("BC", 2:3)
srn.os <- job_seuratn(dirs[useWhich], strx(dirs, "BC[0-9]+")[useWhich])

srn.os <- step1(srn.os, 300, 10000, 10)
srn.os <- step2(srn.os, 4)
srn.os@plots$step2$p.pca_rank
srn.os <- step3(srn.os, 1:10, 1.2)
srn.os@plots$step3$p.umap
vis(srn.os, "orig.ident")
srn.os <- step4(srn.os, "")
srn.os <- step5(srn.os)
srn.os@step <- 5L
srn.os <- step6(srn.os, "Osteosarcoma")
wrap(srn.os@plots$step6$p.map_gpt, 8, 6)
srn.os@plots$step6$p.markers

srn.os@object@assays$integrated
```



```{r eval = T, echo = F, results = "asis"}
#| OS-Markers-in-cell-types
autor(srn.os@plots$step6$p.markers)
```

## CopyKAT 癌细胞鉴定 (BC2)

```{r}
sr.bc2 <- job_seurat("./GSE152048/BC2/", "BC2")
kat.bc2 <- asjob_kat(sr.bc2)
kat.bc2 <- step1(kat.bc2)
kat.bc2 <- step2(kat.bc2)
kat.bc2 <- step3(kat.bc2)
kat.bc2@plots$step3$p.copykat
clear(kat.bc2)
# kat.bc2 <- readRDS("./kat.bc2.3.rds")
```

## CopyKAT 癌细胞鉴定 (BC3)

```{r}
sr.bc3 <- job_seurat("./GSE152048/BC3/", "BC3")
kat.bc3 <- asjob_kat(sr.bc3)
kat.bc3 <- step1(kat.bc3)
kat.bc3 <- step2(kat.bc3)
kat.bc3 <- step3(kat.bc3)
kat.bc3@plots$step3$p.copykat
clear(kat.bc3)
# kat.bc3 <- readRDS("./kat.bc3.3.rds")
```

```{r}
srn.os@object@meta.data
kat.bc2@tables$step2$res_copykat
srn.os <- merge(srn.os, kat.bc2, "ChatGPT_cell")
srn.os <- merge(srn.os, kat.bc3, "copykat_cell")
srn.os <- mutate(srn.os, isCancer = ifelse(copykat_cell == "Cancer cell", "Cancer", "Normal"))
wrap(srn.os$p.map_cancer, 8, 6)
vis(srn.os, "isCancer")
```

## scFEA 单细胞数据的代谢通量预测 (OS)

```{r}
scf.os <- asjob_scfea(srn.os, org = "human")
scf.os <- step1(scf.os)
```


# 总结 {#conclusion}


