---
---

```{r include = F, eval = F}
info <- items(start = td("2026-03-04"), end = td("2026-03-04"), finish = td("2026-03-04"),
  id = "p1639", client = "", inst = "",
  type = "生信分析",
  title = "",
  save = ".items_analysis.rds"
)
show.ic(info)

order_publish.complex("analysis.Rmd", "analysis_out.Rmd")
idname <- formatName.complex("./analysis_out.docx")
order_packaging("./analysis_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.complex(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 项目概述

## 项目背景

## 分析方法

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

## 数据来源

## 研究目标

## 拟解决的关键科学问题

## 创新性

## 流程图

\newpage

# 分析结果 {#workflow}

`r snap(srn.GSE215968, TRUE)`

<!-- LEGEND_END -->


```{r}
gds.ash <- job_gds("Asherman")
gds.ash <- step1(gds.ash, single_cell = TRUE)
gds.ash@object

gds.iua <- job_gds("Intrauterine Adhesion")
gds.iua <- step1(gds.iua, deep_inspect = FALSE)
gds.iua@object
```


```{r}
conflicted::conflict_prefer("map", "utils.tool")

setup.sshfs()
new_script.hb("DEG")
new_script.hb("enrichment")
new_script.hb("ppi")
new_script.hb("learn")
new_script.hb("expression_validate")
new_script.hb("gsea")
new_script.hb("immune")
new_script.hb("nomogram")
new_script.hb("locate")
new_script.hb("network")
new_script.hb("graphBan")
new_script.hb("geneMANIA")
new_script.hb("seurat")
# new_script.hb("seurat_ex")
new_script.hb("cellchat")
new_script.hb("BCellSubType")
new_script.hb("monocle2")
new_script.hb("reactome")

.send_pkg_to_remote()
.upd_pkg_to_remote()

run_in_project_nohup("r.13_seurat.r")
run_in_project_nohup("r.15_seurat_ex.r")
run_in_project_nohup("r.16_monocle2.r")

```

```{r}
fea.markers <- as_feature(c("H1-4", "FXYD7"), ref = "生物标识物基因")
# file.copy("~/Downloads/markers_2.xlsx", "./remote/markers.xlsx")
feature(gb.markers)

vn.drugs <- asjob_vina(gb.markers)
vn.drugs <- step1(vn.drugs, exclude_pdb = "3TZD", forceAF = TRUE)
vn.drugs@params$targets_annotation
vn.drugs@params$used_pdbs
vn.drugs <- step2(vn.drugs)
vn.drugs <- step3(
  vn.drugs, extra_pdb.files = c(
    FXYD7 = "~/Downloads/AF-P58549-F1-model_v6.pdb",
    `H1-4` = "~/Downloads/AF-P10412-F1-model_v6.pdb"
  )
)
vn.drugs$dock_layout
vn.drugs$used_pdbs

# vn.drugs
vn.drugs <- step4(vn.drugs)
vn.drugs@step <- 4L
vn.drugs <- step5(vn.drugs)
vn.drugs@tables$step5$res_dock

vn.drugs@step <- 5L
vn.drugs <- step6(vn.drugs)
vn.drugs <- step7(vn.drugs)
vn.drugs@plots$step6$`Top1_24893490_into_AF-P58549-F1-model_v6`
vn.drugs@plots$step6$`Top2_98104494_into_AF-P10412-F1-model_v6`
vn.drugs@plots$step7$`Top1_24893490_into_AF-P58549-F1-model_v6`
vn.drugs@plots$step7$`Top2_98104494_into_AF-P10412-F1-model_v6`
clear(vn.drugs)

```

```{r}
take_positions({
  des.iua@plots$step3$topDegs$`IUA vs control`$p.hp
  des.iua@plots$step3$topDegs$`IUA vs control`$p.volcano
  des.iua@params$focusedDegs_ARLNC1$p.BoxPlotOfDEGs
  des.iua@params$focusedDegs_ARLNC1$roc$ARLNC1$p.roc
  des.arlnc1@plots$step3$topDegs$`High vs Low`$p.hp
  des.arlnc1@plots$step3$topDegs$`High vs Low`$p.volcano
  vn.iua_arlnc1@plots$step1$p.venn
})

take_positions({
  en.iua_arlnc1@plots$step1$p.kegg$id
  en.iua_arlnc1@plots$step1$p.go$id
})

take_positions({
  ml.iua_arlnc1@plots$step1$p.results
  ml.iua_arlnc1@plots$step2$p.lasso_cv
  ml.iua_arlnc1@plots$step2$p.coefs_path
  ml.iua_arlnc1@plots$step3$p.error
  vn.learn@plots$step1$p.venn
})

take_positions({
  des.validate_train@params$focusedDegs_learn$p.BoxPlotOfDEGs
  lm.validate_gse224093@plots$step2$p.BoxPlotOfDEGs_learn
})

take_positions({
  corgsea.marker@plots$step1$p.gsea$`H1-4`
  corgsea.marker@plots$step1$p.gsea$FXYD7
})

take_positions({
  iobr.iua@plots$step2$p.boxplot
  iobr.iua@plots$step2$p.cor
  iobr.iua@plots$step3$p.GeneCellCor
})

take_positions({
  rms.iua@plots$step1$p.nomo
  rms.iua@plots$step1$p.rocs
  rms.iua@plots$step1$p.cal
  rms.iua@plots$step2$p.dcas
})

take_positions({
  lc.markers@plots$step1$p.locateChr
  lc.markers@plots$step2$p.locateScore
})

take_positions({
  rn.markers@plots$step5$p.regNet
})

take_positions({
# spsv(srn.GSE215968@plots$step2$p.pca_rank, "pca_rank")
# spsv(z7(srn.GSE215968@plots$step3$p.umapUint, 1.5, 1), "umapUint")
# spsv(z7(.vis_seurat_label(srn.GSE215968), 1.5, 1), "umapInt")
# spsv(wrap(test$p.qc_aft, 20, 15), "qc_aft")
# spsv(wrap(srn.GSE215968$p.qc_pre, 20, 15), "qc_pre")
})

take_positions({
  srn.GSE215968@plots$step6$p.markers
  srn.GSE215968@plots$step6$p.map_scsa
  srn.GSE215968@plots$step6$p.props_scsa
  srn.GSE215968@plots$step6$p.props_scsa_stat
  # srn.GSE215968$focus_by_group$plist.vlnFacet$HIST1H1E
})
scsa_check(srn.GSE215968, "B cells")

take_positions({
  srn.GSE215968$focus_by_cell$p.dim
  srn.GSE215968$focus_by_cell$p.dot
  srn.GSE215968$focus_by_group$plist.vlnFacet$HIST1H1E
  srn.GSE215968$focus_by_group$plist.vlnFacet$FXYD7
})

take_positions({
  cc.comparison@plots$step1$p.inters_counts
  cc.comparison@plots$step1$p.inters_weights
  cc.comparison@params$each_lr_comm$p.lr_comm_bubbles$IUA
  cc.comparison@params$each_lr_comm$p.lr_comm_bubbles$Control
  cc.comparison@params$each_lr_comm$t.lr_comm_bubble
})

take_positions({
  srn.GSE215968_B_cells@plots$step6$p.markers
  srn.GSE215968_B_cells@plots$step6$p.map_scsa
  srn.GSE215968_B_cells@plots$step3$p.umapLabel
})
srn.GSE215968_B_cells@meth

take_positions({
  mn.GSE215968_B_cells@plots$step3$p.traj
  mn.GSE215968_B_cells@plots$step4$p.geneInPseudo$group
  mn.GSE215968_B_cells@plots$step4$p.geneInPseudo$scsa_cell
})

# cc.GSE215968_iua@tables$step2$t.lr_comm_bubble$prob
# cc.GSE215968_control@tables$step2$t.lr_comm_bubble
graphics.off()


```




```{r eval = T, echo = F, results = "asis"}
#| GSE215968-dimension-plot-of-by-cell
autor(srn.GSE215968$focus_by_cell$p.dim)
```


```{r eval = T, echo = F, results = "asis"}
#| IUA-ARLNC1-Intersection-of-IUA-Control-with-ARLNC1-HL
autor(vn.iua_arlnc1@plots$step1$p.venn)
```



