---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(1), coef = NA)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

- 质谱对复方内的五味药萆薢、土茯苓、泽泻、川牛膝和生米仁进行预测，得到复方药物的具体的有效药物成分XX1、XX2、XX3
- 分子对接检测XX1、XX2、XX3与FOXO信号的对接能量
- 通过GO功能富集分析和KEGG通路富集分析，对FOXO信号通路的下游靶点进行预测，进而得到所需的关于抑制炎症的下游靶点YY

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))
```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
db <- readxl::read_xls("/media/echo/6E3CE3153CE2D75D/王陈芳质谱结果/FT231221067-原始数据/活性成分附表-FT231221067-Y.xls")

fun_format <- function(x) {
  x <- dplyr::filter(x, !is.na(...3))
  x <- dplyr::select_if(x, function(x) !all(is.na(x)))
  x <- dplyr::select(x, name = ...3, rt.min = ...7, formula = ...9, mw = ...12)
  x <- dplyr::filter(x, name != "Name")
  pos.na <- which(is.na(x$rt.min))
  pos.napre <- pos.na - 1
  str.na <- x$name[ pos.na ]
  x$name[ pos.napre ] <- paste0(x$name[ pos.napre ], x$name[ pos.na ])
  x <- dplyr::filter(x, !is.na(rt.min))
  x <- dplyr::mutate(x, en.name = gs(name, "([^\u4e00-\u9fa5]*).*", "\\1"),
    cn.name = gs(name, ".*?([\u4e00-\u9fa5].*)$", "\\1"),
    tail = strx(en.name, " [^ ]+-$"),
    tail = ifelse(is.na(tail), "", tail),
    en.name = substr(en.name, 1, nchar(en.name) - nchar(tail)),
    en.name = gs(en.name, "\\s*$", ""),
    cn.name = gs(paste0(tail, cn.name), "^\\s*", ""),
    formula = gs(formula, "\\s", ""),
    rt.min = round(as.double(rt.min), 2),
    mw = round(as.double(mw), 4)
  )
  x <- dplyr::select(x, -tail, -name)
  dplyr::relocate(x, en.name, cn.name)
}

table <- fun_format(db)

file.copy("/media/echo/6E3CE3153CE2D75D/王陈芳质谱结果/FT231221067-原始数据/活性成分附表-FT231221067-Y.xlsx", "./order_material")
dir.create("./material")
unzip("./order_material/活性成分附表-FT231221067-Y.xlsx", exdir = "./material")

fun <- function(dir) {
  files <- list.files(dir, ".png$", full.names = T)
  scale <- sapply(files, simplify = F,
    function(x) {
      try(bitmap_info(x))
    })
  scale <- frbind(scale, idcol = "file")
  scale <- dplyr::filter(scale, width > height * 15)
  scale <- dplyr::mutate(scale, num = as.integer(gs(file, ".*?([0-9]+).png", "\\1")))
  scale <- dplyr::arrange(scale, num)
}
scales <- fun("./material/xl/media/")

oc <- job_ocr()
oc <- step1(oc)
res <- map(oc, head(scales$file, n = 1))


```

## LC-MS

```{r}
path <- "/media/echo/6E3CE3153CE2D75D/王陈芳质谱结果/FT231221067-原始数据/"
files <- list.files(path, ".raw$")

msc <- job_msconvert(path, files)
msc.neg <- step1(msc, "neg")
msc.pos <- step1(msc, "pos")

```

### Neg

```{r}
xc.neg <- asjob_xcms(msc.neg)
xc.neg <- step1(xc.neg)
xc.neg <- step2(xc.neg)

si.neg <- asjob_sirius(xc.neg)
si.neg <- set_remote(si.neg, "/data/hlc/wangchengfang_neg")
si.neg@step <- 0L
si.neg <- step1(si.neg)
si.neg <- step2(si.neg, NULL, workers = 30)

si.neg <- step3(si.neg)
ping(si.neg)



```

### Pos

```{r}

```

```{r}
saves()
loads()
```
