---
---

```{r include = F, eval = F}
info <- items(start = td("2025-02-27"), end = td("2025-03-05"), finish = td(NA),
  id = "BSCL250222", client = "汪光亮", inst = "",
  type = "生信分析",
  title = "MYLK分子对接",
  save = ".items_analysis.rds"
)
show.ic(info)

order_publish.bosai("analysis.Rmd", "analysis_out.Rmd")
idname <- formatName.bosai("./analysis_out.docx")
order_packaging("./analysis_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

## BindingDB 药物靶点数据获取 (MYLK)

`r snap(bdb.mylk, 0:2)`

```{r}
bdb.mylk <- job_bindingdb()
#' @meth {get_meth(bdb.mylk)}
bdb.mylk <- step1(bdb.mylk, symbol = "MYLK")
bdb.mylk <- step2(bdb.mylk)
bdb.mylk$annotation
```

## AutoDock vina 分子对接 (MYLK)

`r snap(vn.mylk, 0:7)`

```{r}
vn.mylk <- asjob_vina(bdb.mylk)
#' @meth {get_meth(vn.mylk)}
vn.mylk <- step1(vn.mylk, FALSE)
vn.mylk <- step2(vn.mylk, FALSE)

vn.mylk <- step3(vn.mylk)

```


# 总结 {#conclusion}

