---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(4), eval = ic(0, 0, 0, 0, 1))
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

需求：蛋白质数据差异分析和火山图绘制

结果：

- Model vs Control 火山图见 Fig. \@ref(fig:PRO-Model-vs-Control-DEPs)，对应数据见 Tab. \@ref(tab:PRO-data-Model-vs-Control-DEPs)
- 除了 Model vs Control, 其他组别数据也已提供，见 \@ref(groups)

注：分析所使用的数据来源于 <http://101.66.242.136:5212/s/r7MTk?path=%2F> 中的 'txt/peptides.txt'

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 差异分析和火山图绘制

### Model vs Control

```{r eval = T, echo = F, results = "asis"}
#| PRO-Model-vs-Control-DEPs
autor(lm.pro@plots$step2$p.valcano$`Model - Control`)
```

```{r eval = T, echo = F, results = "asis"}
#| PRO-data-Model-vs-Control-DEPs
autor(lm.pro@tables$step2$tops$`Model - Control`, key = "gene_name")
```

### Other Group {#groups}

```{r eval = T, echo = F, results = "asis"}
#| All-volcano-plots
autor(lm.pro@plots$step2$p.valcano)
```

```{r eval = T, echo = F, results = "asis"}
#| ALL-data-DEPs
autor(lm.pro@tables$step2$tops)
```

```{r eval = T, echo = F, results = "asis"}
#| RAW-quantification
autor(quant)
```

```{r}
quant <- ftibble("/media/echo/6E3CE3153CE2D75D/史晓林/peptides.txt")

quant <- dplyr::select(quant, Proteins, Mass, id, dplyr::starts_with("Intensity"),
  dplyr::contains("MS/MS"), dplyr::starts_with("LFQ"))

dat <- dplyr::select(quant, id, Proteins, dplyr::starts_with("LFQ"))
dat <- dplyr::mutate(dat, uniprot_entry = strx(Proteins, "(?<=\\|)[^\\|]+(?=\\|)"))
dat <- dplyr::relocate(dat, uniprot_entry)
dat

mapped <- UniProt.ws::mapUniProt(
  from = "UniProtKB_AC-ID",
  to = "Gene_Name",
  query = list(ids = unique(dat$uniprot_entry))
)
mapped

dat <- map(dat, "uniprot_entry", mapped, "From", "To", col = "gene_name")
dat <- dplyr::relocate(dat, gene_name)

counts <- dplyr::select(dat, id, dplyr::where(is.double))
genes <- dplyr::select(dat, id, dplyr::where(is.character))

metadata <- group_strings(colnames(dat),
  c("Control" = "CONTROL", "Model" = "MODEL", "Low" = "LOW", "Middle" = "MIDDLE",
    "High" = "HIGH"), "sample")

lm.pro <- job_limma(new_dge(metadata, counts, genes))
lm.pro <- step1(lm.pro)
lm.pro$seed <- 33L
lm.pro <- step2(lm.pro,
  Model - Control, Low - Model, Middle - Model, High - Model,
  High - Middle, Middle - Low,
  label = "gene_name", cut.fc = 1
)

lm.pro@plots$step2$p.valcano$`Model - Control`
lm.pro@plots$step2$p.valcano$`High - Middle`
```


