
### 构建 PPI 网络

```{r}
st <- job_stringdb(data.frame(hgnc_symbol = treat_all))
st <- step1(st, tops = 50)
st@plots$step1$p.mcc
st.hub50 <- head(st@tables$step1$hub_genes, n = 50)$hgnc_symbol
intersect(st.hub50, geo.plots$p.upset.ins)
```

### 富集分析

```{r}
en <- job_enrich(list(ids = coTarget), anno)
en <- step1(en)
en@plots$step1$p.go$ids
en <- step2(en)
```

### GSE232753: Comparative gene expression profiling analysis of RNA-seq data for patients with sepsis and healthy volunteer.

```{r}
geo1 <- job_geo("GSE232753")
geo1 <- step1(geo1)
geo1 <- step2(geo1)

geo1@params$guess
```

### GSE224095: Single-cell transcriptomic changes in sepsis patient

```{r}
geo2 <- job_geo("GSE224095")
geo2 <- step1(geo2)
geo2 <- step2(geo2)

geo2@params$guess
```

## TNA 靶点基因

TNA (Tanshinone I) 靶点基因

```{r}
tna_tgt <- fxlsx("./raw/tna_targets.xlsx")
```

为了筛选出有关肠道微生物的DEGs，优先针对 colon sepsis 的 DEGs 分析。

```{r}
mj <- esearch.mj("microbiota RNA-seq")
dplyr::select(mj, .id, Title)
```

```{r}
en1 <- job_enrich(list(ids = ins(treat_all, colon.DEGs)), anno)
en1 <- step1(en1)

db.c2 <- get_c2_data("micro")
```

```{r}
# colon.DEGs <- geo.plots$upset.set$colon
gdb <- ftibble("../Gut Microbe and Metabolite-human.txt")
```

```{r}
data <- fxlsx("~/Downloads/Table_1.xlsx")
data <- dplyr::mutate_at(data, 2:ncol(data),
  function(x) {
    x <- as.double(x)
    ifelse(is.na(x), 0, x)
  })
rownames(data) <- data$Metabolites
data <- dplyr::select(data, -1)

data <- new_heatdata(as_data_long(data))
callheatmap(data)
```
