---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(3), coef = NA, eval = ic(0, 0, 1, 0, 0))

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"),
  di("脓毒症")
)

# DEGs: Differential Expressed Genes 差异表达基因
# S: sepsis 脓毒症
```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}


## 数据来源


Lipid metabolic signatures deviate in sepsis survivors compared to non-survivors
(PMID:33304464) [@LipidMetabolicKhaliq2020]

Supplementary Table 7: Rat sepsis model biochemical and metabolomic data.

```{r eval = T, echo = F, results = "asis"}
#| LipidMetabolicKhaliq2020-S7
autor(lst)
```

```{r}
lst <- fxlsx2("./material/LipidMetabolicKhaliq2020_s7.xlsx", bind = F, sep.names = " ")
legend <- dplyr::mutate(lst$legend, name = ifelse(is.na(name), X1, name))

dat <- dplyr::filter(lst$Data, material == "plasma")
dat <- dplyr::mutate(dat, sub_group = group,
  group = ifelse(sub_group == "control", "Control", "Sepsis"),
  sample = paste0(group, "_", `Sample Identification`)
)
metadata <- dplyr::select(dat, sample, group)
dat <- dplyr::select(dat, sample, dplyr::where(is.double))
dat <- dplyr::arrange(dat, sample)

fun_format <- function() {
  samples <- dat$sample
  dat <- data.frame(t(dat[, -1]))
  colnames(dat) <- samples
  dat <- dplyr::mutate(dat, cpd = rownames(dat))
  dat <- tibble::as_tibble(dat)
  dat <- dplyr::relocate(dat, cpd)
}
dat <- fun_format()
dat <- map(dat, "cpd", legend, "X1", "name")
dat <- dplyr::mutate(dat, name = gs(name, "^\\s+|\\s+$", ""))
dat <- dplyr::mutate_if(dat, is.double, log2)
pattern <- "GAP|DHAP|Serine|glycine|pyruvate|lactate"
dplyr::filter(dat, grpl(name, pattern, T))

```

## 差异分析

```{r eval = T, echo = F, results = "asis"}
#| Sepsis-vs-Control-metabolites
autor(lm@tables$step2$tops$`Sepsis - Control`)
```

```{r}
lm <- job_limma_normed(dat, metadata)
lm <- step1(lm)
lm <- step2(lm, Sepsis - Control, use = "P")
lm@plots$step2$p.valcano$`Sepsis - Control`
tops <- lm@tables$step2$tops$`Sepsis - Control`

dplyr::filter(tops, grpl(rownames, pattern, T))
tops$rownames == "Lactate"
```

## 热图

注：以下热图去除了包含缺失数据的代谢物。

```{r eval = T, echo = F, results = "asis"}
#| Defferential-metabolites
autor(wrap(hp, 11, 10))
```

```{r}
file.copy("~/Downloads/mmc7.xlsx", "./material/LipidMetabolicKhaliq2020_s7.xlsx")
```

```{r}
hp.dat <- dplyr::select(dat, -Sepsis_048P, -Control_078P)
notUse <- apply(hp.dat[, -1], 1, function(x) any(is.na(x) | is.infinite(x)))
hp.dat <- dplyr::filter(hp.dat, !(notUse))
hp.dat <- dplyr::filter(hp.dat, name %in% tops$rownames, !grpl(name, "Phos"))
hp.dat <- dplyr::mutate_if(hp.dat, is.double, function(x) scale(x, scale = F)[, 1])

hp <- new_heatdata(hp.dat)

hp@xmeta <- dplyr::distinct(metadata, sample, group)
hp <- callheatmap(hp)
hp
```

