---
---

```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
path <- fxlsx("./order_material/Ssb1VSCCl4_KEGG_enrichment_Gene.xlsx")
path <- select(path, -Description)
path <- rename(path, Symbol = Gene_name, Description = pathway_name)

n <- 10L
data <- dplyr::summarize(dplyr::group_by(path, Description, pvalue),
    gene_ratio = length(Symbol) / length(unique(path$Symbol)))
data <- arrange(data, pvalue)
data <- head(data, n = n)
data <- mutate(dplyr::ungroup(data), path.p = nrow(data):1)

target <- "ECM-receptor interaction"
edges <- distinct(path, Symbol, Description, log2fc = `log2(fc)`)
edges <- filter(edges, Description %in% !!target)

nodes <- tidyr::gather(edges, type, name, -log2fc)
nodes <- split(nodes, ~type)
nodes$Symbol <- arrange(nodes$Symbol, log2fc)
nodes$Symbol <- mutate(
  nodes$Symbol, x = 0L,
  y = seq(1, n, length.out = length(name))
)
nodes$Description <- distinct(nodes$Description, type, name)
nodes$Description <- mutate(
  nodes$Description, x = 1L,
  y = data$path.p[ match(name, data$Description) ]
)
nodes <- data.table::rbindlist(nodes, fill = T)
nodes <- select(nodes, x, y)

graph <- fast_layout(edges, select(nodes, x, y), nodes = select(nodes, name))

p <- ggraph(graph) +
    geom_edge_fan(aes(x = x, y = y),
      start_cap = circle(sc, 'mm'),
      end_cap = circle(ec, 'mm'),
      # arrow = arrow(length = unit(arr.len, 'mm')),
      color = edge.color, width = edge.width) +
    geom_node_point(aes(x = x, y = y, fill = ifelse(is.na(MCC_score), 0, MCC_score)),
      size = node.size, shape = 21, stroke = .3) +
    geom_node_text(aes(label = !!rlang::sym(label)), size = label.size) +
    scale_fill_gradient(low = "lightyellow", high = "red") +
    scale_x_continuous(limits = zoRange(graph$x, scale.x)) +
    scale_y_continuous(limits = zoRange(graph$y, scale.y)) +
    labs(fill = "MCC score") +
    theme_void() +
    theme(plot.margin = margin(r = .05, unit = "npc")) +
    geom_blank()

```
