---
---

```{r include = F, eval = F}
info <- items(start = td("20240326"), end = td("20241206"), finish = td("20241204"),
  id = "BSHQ240303", client = "张永旭", inst = "大连医科大学附属第二医院骨科",
  type = "生信分析",
  title = "ZDHHC15互作蛋白筛选",
  save = ".items_analysis_inter.rds"
)
show.ic(info)

order_publish.bosai("analysis_inter.Rmd", "analysis_inter_out.Rmd")
idname <- formatName.bosai("./analysis_inter_out.docx")
order_packaging("./analysis_inter_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table_inter", tabs = "Figure+Table_inter"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

## 需求

根据结果选择ZDHHC15做后续实验，需要继续做一个蛋白互作网络，看看ZDHHC15结合的什么分子，结合分数多少。（用骨肉瘤的基因集，构建蛋白互作网络。 筛选ZDHHC15结合的分子，依据结合分数，确认下游靶蛋白）。
补充要求，互作蛋白首选铁死亡促进因子/基因。

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

## FerrDb 铁死亡调控因子 (FERR)

```{r}
#' @meth {get_meth(fe.ferr)}
fe.ferr <- job_fe()
fe.ferr <- step1(fe.ferr, collate = T)
fe.ferr@plots$step1$p.ferroptosisRegulatorsDistribution
fe.ferr@tables$step1$t.ferroptosisRegulators$driver
tbl_fe.ferr_drive <- fe.ferr@tables$step1$t.ferroptosisRegulators$driver

fe.ferr@tables$step1$t.ferroptosisRegulators
list_fe.ferr_tferr <- fe.ferr@tables$step1$t.ferroptosisRegulators

```

## STRINGdb PPI 分析 (ZD-DRIVER)

```{r}
sdb.zdDriver <- job_stringdb(c("ZDHHC15", list_fe.ferr_tferr$driver$symbol))
sdb.zdDriver <- step1(sdb.zdDriver, network_type = "full")
sdb.zdDriver@plots$step1$p.ppi

dplyr::filter(sdb.zdDriver@params$edges, from == "ZDHHC15" | to == "ZDHHC15")

lstSdb.zdDriver <- filter(sdb.zdDriver, "ZDHHC15", sdb.zdDriver@object$Symbol,
  use.top = "to", keep.ref = F, top = Inf)
lstSdb.zdDriver$edges

```

```{r}
lm.geoOs4 <- readRDS("./lm.geoOs40.rds")
lm.geoOs4 <- step1(lm.geoOs4)
lm.geoOs4 <- step2(lm.geoOs4, TUMOUR - NORMAL, label = "hgnc_symbol", use = "P")
lm.geoOs4@tables$step2$tops$`TUMOUR - NORMAL`
tbl_lm.geoOs4_TUMOU <- lm.geoOs4@tables$step2$tops$`TUMOUR - NORMAL`
dplyr::filter(tbl_lm.geoOs4_TUMOU, hgnc_symbol %in% lstSdb.zdDriver$edges$to)
```

```{r}
lm.geoOs <- readRDS("./lm.geoOs0.rds")
lm.geoOs <- step1(lm.geoOs, data_type = "cpm")
lm.geoOs <- step2(lm.geoOs, OS - Normal, label = "Symbol", use = "P")
lm.geoOs@tables$step2$tops$`OS - Normal`
tbl_lm.geoOs_OSNor <- lm.geoOs@tables$step2$tops$`OS - Normal`
dplyr::filter(tbl_lm.geoOs_OSNor, Symbol %in% lstSdb.zdDriver$edges$to)
```


# 总结 {#conclusion}

```{r}
loads("./workflow_inter.rdata")

saves("./workflow_inter.rdata")
```
