---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(3), eval = ic(0, 0, 0, 0, 1))

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 数据预处理

```{r}
browseURL("./order_material/数据-2024010202.docx")
browseURL("./order_material/原始数据/2024010202 原始数据.xlsx")

vars <- c("舒张压", "心功能分级", "肌酐", "CRP", "NT", "TBIL", "RDW")

Raw <- fxlsx2("./order_material/原始数据/2024010202 原始数据.xlsx", 1:2, "Group")
dat <- dplyr::select(Raw, Group, dplyr::matches(paste0(paste0("^", vars), collapse = "|")))
colnames(dat) %<>% gs("\\.", " ")
dat <- dplyr::mutate(dat, Group = gs(Group, "组 .*", ""),
  Group = as.factor(Group),
  `心功能分级` = dplyr::recode(`心功能分级`, '1' = "I-II 级", '2' = "I-II 级", '3' = "III-IV 级", '4' = "III-IV 级"),
  `心功能分级` = as.factor(`心功能分级`)
)
dat <- dplyr::filter(dat, !is.na(`心功能分级`))
dat

```

## 结果

```{r eval = T, echo = F, results = "asis"}
autor(lrm.heart$fit)
```

```{r eval = T, echo = F, results = "asis"}
#| heart-Nomogram-plot
autor(wrap(nomo.heart$p.nomo, 13, 6.5))
```

```{r eval = T, echo = F, results = "asis"}
#| heart-Bootstrap-calibration
autor(lrm.heart$p.cal)
```

```{r eval = T, echo = F, results = "asis"}
#| heart-ROC
autor(lrm.heart$roc$p.roc)
```


```{r}
lrm.heart <- new_lrm(dat, "Group", rev.level = T)
nomo.heart <- new_nomo(lrm.heart, fun_at = seq(.1, 1, by = .3))
nomo.heart$p.nomo
```

