---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(4), eval = ic(1, 2, 0, 1, 0))
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

- 复方：地黄15g、黄芪15g、葛根18g、石斛15g、水蛭3g、川芎9g
- 有效成分：水蛭中水蛭素 Hirudin（重点关注）
- 疾病：缺血性脑卒中
- 机制：血管生成
- 目标：找到水蛭素通过XX靶点及XX靶点涉及的通路YY影响缺血性脑卒中的血管生成

请注意，网药有效成分筛选时确认包括水蛭素，如不包括，请及时联系
 

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
herbs <- c("地黄", "黄芪", "葛根", "石斛", "水蛭", "川芎")

tc2 <- job_tcmsp2(herbs)
tc2 <- step1(tc2)
tc2 <- step2(tc2)
```

```{r}
bt <- job_batman(herbs)
bt <- step1(bt)
bt@tables$step1$herbs_compounds
```

```{r}
dl <- job_dl()
```
