---
---

```{r include = F, eval = F}
info <- items(start = td("2024-11-21"), end = td("2025-03-21"), finish = td(NA),
  id = "BSJF241107", client = "", inst = "",
  type = "生信协助",
  title = "脓毒症",
  save = ".items_support.rds"
)
show.ic(info)

order_publish.bosai("support.Rmd", "support_out.Rmd")
idname <- formatName.bosai("./support_out.docx")
order_packaging("./support_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

1. 哪种类型T细胞起主要作用（参考一下这篇文章PMID：38291496）？
2. 筛选15个基因太多，能不能在缩减一下，主要看下这几个基因富集的信号通路或者生物学途径。

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

```{r}
sr.sepsis <- readRDS("./sr.sepsis.4.rds")
sr.t_cell <- getsub(sr.sepsis, cells = which(meta(sr.sepsis)$Cell_Type == "T"))
rm(sr.sepsis)

t_cell_markers <- list(
  # T_cell_general = c("CD3D", "CD3E", "CD3G", "TRAC"),
  CD4_naive = c("CD4", "CCR7", "LEF1", "SELL"),
  CD4_memory = c("CD4", "IL7R", "CCR6"),
  CD8_naive = c("CD8A", "CCR7", "LEF1"),
  CD8_cytotoxic = c("CD8A", "GZMB", "PRF1", "IFNG"),
  Treg = c("CD4", "FOXP3", "IL2RA", "CTLA4"),
  Th1 = c("CD4", "TBX21", "CXCR3", "IFNG"),
  Th2 = c("CD4", "GATA3", "CCR4", "IL4"),
  Th17 = c("CD4", "RORC", "CCR6", "IL17A"),
  Tfh = c("CD4", "BCL6", "CXCR5", "IL21"),
  γδ_T = c("TRDC", "TRGC1", "TRGC2"),
  MAIT = c("SLC4A1", "KLRB1", "RORC"),
  NKT = c("CD3D", "KLRB1", "NKG7"),
  Activated_T = c("CD69", "HLA-DRA", "CD38"),
  Exhausted_T = c("PDCD1", "LAG3", "TIGIT")
)

ref.markers <- as_df.lst(t_cell_markers, "cell", "markers")
ref.markers

sr.t_cell@step <- 2L
sr.t_cell <- step3(
  sr.t_cell, 1:5, .5, reset = TRUE, force = TRUE, features = ref.markers$markers
)
Seurat::ElbowPlot(object(sr.t_cell), reduction = "features_pca")

sr.t_cell@plots$step3$p.umap
sr.t_cell <- step4(sr.t_cell, "")

# set_remoteRun.bosai()
# sr.t_cell <- set_remote(sr.t_cell)
sr.t_cell <- step5(sr.t_cell, 5, force = TRUE)

sr.t_cell@step <- 5L
sr.t_cell <- step6(
  sr.t_cell, "blood", ref.markers, keep_markers = 5
)
sr.t_cell@plots$step6$p.map_scsa
sr.t_cell@plots$step6$p.markers

```

# 总结 {#conclusion}

