---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(4), eval = ic())
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
herbs <- c("黄芪", "川牛膝", "桃仁", "大黄", "车前草")

tc2 <- job_tcmsp2(herbs)
tc2 <- step1(tc2)
tc2@step <- 1L
tc2$queries <- herbs
tc2 <- step2(tc2)
tc2@tables$step2

saveRDS(tc2@tables$step2, "herb.rds")

tc2@params$dbs$ingredients@db %<>% dplyr::filter(!is.na(MW))


```
