---
---

```{r include = F, eval = F}
info <- items(start = td("2026-02-19"), end = td("2026-02-19"), finish = td("2026-02-19"),
  id = "test", client = "", inst = "",
  type = "index",
  title = "",
  save = ".items_index.rds"
)
show.ic(info)

order_publish.complex("index.Rmd", "index_out.Rmd")
idname <- formatName.complex("./index_out.docx")
order_packaging("./index_out.docx", idname = idname, external_file = NULL)

build_completion_for_package("utils.tool")
readRDS("~/.cache/R.nvim/extra_completion_packages.rds")
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.complex(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

## BATMAN 网络药理学 (LIANZI)

`r ref("LIANZI-Prediction-of-HOB-and-Drug-Likeness")`
<!-- LEGEND_END -->

```{r}
bat.lianzi <- job_batman(c("莲子"))
bat.lianzi <- step1(bat.lianzi)
bat.lianzi <- step2(bat.lianzi)
bat.lianzi <- step3(bat.lianzi)
bat.lianzi@plots$step1$p.upset
```


```{r eval = T, echo = F, results = "asis"}
#| LIANZI-Prediction-of-HOB-and-Drug-Likeness
autor(bat.lianzi@plots$step1$p.upset)
```

