---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
output:
  custom_docx_document2:
    reference_docx: '`r system.file("extdata", "bosai.docx", package = "utils.tool")`'
---


```{r include = F, eval = F}
info <- items(start = td("2024-08-20"), end = td("2025-04-11"), finish = td("2025-04-17"),
  id = "BSJF240719", client = "", inst = "",
  type = "模块开发",
  title = "代谢组学数据分析流程",
  note = "",
  save = ".items_module.rds"
)
show.ic(info)

order_publish.bosai("module.Rmd", "module_out.Rmd")
formatName.bosai("./module_out.docx")
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"), autor_asis = F)
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

## 思路

```{r}
#| route
route <- as_network(
  list(
    "主题/疾病:GNPS_数据库检索:原始数据获取:数据格式转换mzML:XCMS数据预处理:导出:quant.csv, msms.mgf",
    "quant.csv:半定量分析:差异分析:MCnebula2",
    "msms.mgf:代谢物鉴定:已知人源代谢物, 未知代谢物预测",
    "已知人源代谢物:HMDB等数据库",
    "未知代谢物预测:SIRIUS_预测:MCnebula2:化学星云分析:系统化学归类, Top代谢物追踪, 化学转变推测:差异代谢物",
    "差异代谢物:关联肠道菌:gutMDisorder_数据库"
    ), "sugiyama"
)
p.route <- flowChart(route, 1.1, 1)
p.route
```

```{r eval = T, echo = F, results = "asis"}
#| Route
autor(p.route)
```

- 参考 <https://mcnebula.org/>。
- <https://github.com/Cao-lab-zcmu/MCnebula2>
- `r cite_show("MCnebula_Criti_Huang_2023")`
- `r cite_show("Molecular_netwo_Chen_2025")`
- `r cite_show("MCnebula_analys_Liu_R_2025")`
- `r cite_show("@ADeepClusteriLaiJ2022")`

## 程序

<https://github.com/shaman-yellow/utils.tool/tree/master/R>

`r bind(list.files("~/utils.tool/R/", pattern = "sirius|msconvert|xcms"), co = "\n\n")`

