---
---

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
deparse_mail()
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

preeclampsia, PE

<https://mp.weixin.qq.com/s?__biz=Mzg2Mjg4OTI2Mw==&mid=2247498654&idx=3&sn=713da5430e5b4daae2ad3bd222a96b32&chksm=ce024fdef975c6c8f49ba37bf5243a1e8954f2e917eef759dbcddfa0361503d42b1aa4ce1348&mpshare=1&scene=24&srcid=0619w5chTx4O60lNBB3FcHiv&sharer_sharetime=1687128996048&sharer_shareid=b9fc51b0646cc26770ccfba2790fc2dd#rd>

Identification of Bioactive Compounds and Potential Mechanisms of Kuntai
Capsule in the Treatment of Polycystic Ovary Syndrome by Integrating Network
Pharmacology and Bioinformatics

- DisGeNet <https://www.disgenet.org/downloads#> OK
- Genecards <https://www.genecards.org/> OK
- PharmGKB <https://www.pharmgkb.org/downloads> OK
- OMIM <https://www.omim.org/downloads> OK

- NCBI <https://www.ncbi.nlm.nih.gov/>

# 前言 {#introduction}

# 研究设计流程图 {#route}

```{r}
#| route
route <- as_network(
  list("RNA_seq_data:Preprocess",
    ), "tree"
)
p.route <- flowChart(route, 1.1, 1)
```

```{r, eval = T, echo = F, fig.width = 10, fig.height = 7, fig.cap = NULL}
p.route
```

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}
