---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \definecolor{shadecolor}{RGB}{242,242,242}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
---


```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover("ST 和 IMS 联合分析")
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

## 2-48512+曹卓+补实验

### 代谢物的表达

```{r eval = T, echo = F, results = "asis"}
#| metabolites-expression
autor(data.m)
```

```{r}
data.m <- ftibble("./tabs/metabolites-expression.csv")
```

### 代谢物和代谢通路在细胞亚群中的动态变化

```{r eval = T, echo = F, results = "asis"}
#| metabolites-expression-in-pseudotime-of-cancer-subtypes
autor(m.pseu)
```

```{r}
m.pseu <- ftibble("./tabs/metabo-coords.csv")
```

### 肿瘤/上皮细胞和免疫细胞的相互作用

```{r eval = T, echo = F, results = "asis"}
#| cell-communication-probability-of-PATHWAY
autor(cc.comm)
```

### 肿瘤/上皮细胞和免疫细胞的代谢作用

```{r eval = T, echo = F, results = "asis"}
#| cells-metabolite-levels
autor(ic.metabo)
```

```{r}
ic.metabo <- ftibble("./tabs/cancer-metabo-level.csv")
```

## 7-48470+曹卓+补实验

### 肿瘤/上皮细胞和免疫细胞的代谢作用

```{r eval = T, echo = F, results = "asis"}
#| cell-metabolites-levels-average
autor(ic.metabo2)
```

```{r}
ic.metabo2 <- ftibble("./tabs/cancer-metabo-level.csv")
ic.metabo2 <- dplyr::summarize(dplyr::group_by(ic.metabo2, scsa_copykat, KEGG), mean = mean(value))
```

## 6-45140+曹卓+补实验

### 代谢物和代谢通路在细胞亚群中的动态变化

```{r eval = T, echo = F, results = "asis"}
#| metabolites-expression-in-pseudotime-average-levels
autor(m.pseu2)
```

```{r}
m.pseu2 <- dplyr::summarize(dplyr::group_by(m.pseu, KEGG, round(pse)), mean = mean(value))
```

### 肿瘤/上皮细胞和免疫细胞的相互作用

```{r eval = T, echo = F, results = "asis"}
#| cell-communication-probability-of-LIGAND-RECEPTORs
autor(cc.comm.lp)
```

# 材料和方法 {#methods}

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

```{r}
sr <- readRDS("~/disk_sdb1/2023_10_06_lunST/st.6.rds")
table(ids(sr, "scsa_copykat", unique = F))

cc <- readRDS("~/disk_sdb1/2023_10_06_lunST/cc.2.rds")
cc.comm <- cc@tables$step1$pathway_net

cc.comm.lp <- cc@tables$step1$lp_net
```

