---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(06), eval = ic(), lock = T)
show.ic(info)

order_publish("./index2.Rmd", "./output2.Rmd")
idname <- order_packaging("./output2.pdf", idname = "re-map")
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

```{r}
fig1 <- cls(
  cl("./Figure+Table/Treat-vs-control-DEGs.pdf"),
  cl("./Figure+Table/DEG-hsa04310-visualization.png")
)
fig1 <- render(fig1)
fig1
```

```{r eval = T, echo = F, results = "asis"}
#| MAIN-Fig-1
autor(fig1)
```

```{r}
fig2 <- cls(
  # rw(),
  rw("./Figure+Table/SCSA-Cell-type-annotation.pdf"),
  rw("./Figure+Table/Violing-plot-of-Wnt-DEGs-of-Curcumin-affected.pdf")
)
fig2 <- render(fig2)
fig2
```

```{r eval = T, echo = F, results = "asis"}
#| MAIN-Fig-2
autor(fig2)
```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}


```{r}
tiffs <- generate_tiffs(output = "TIFF2")
```

```{r eval = T, echo = F, results = "asis"}
#| Tiff-figures
autor(tiffs)
```

# 结论 {#dis}


```{r eval = T, echo = F, results = "asis"}
set_appendix()
```

# 附：分析流程 {#workflow}


