董志霞反馈分组情况如下:
18个小鼠，
chow（正常组）1,2,3,4,5,6
LD（结石组）1,2,3,4,5,6
sev（治疗组）1,2,3,4,5,6

结石组的造模方式？
致石饲料加治疗药物

治疗组的造模方式？
盐酸司维拉姆



- 质控
    - fastp
- 去宿主序列
    - bowtie2 <https://github.com/BenLangmead/bowtie2>
- 组装 assembly
    - megahit <https://github.com/voutcn/megahit>
- 分箱 binning
- 功能基因预测

组装分析：发现新物种和其基因组
免组装群落分析：以参考数据库注释群落，发现差异菌

```{r}

rem_list.files("/data/hlc/dongzhixia3/", ".", recursive = T)

bw <- asjob_bowtie2(fp, 20)
bw <- step1(bw)
bw <- step2(bw)


```



```{r}
# https://zhuanlan.zhihu.com/p/105602400

# biob
# https://zhuanlan.zhihu.com/p/496984933

# https://www.jianshu.com/p/c981cdd8fce8

# 关于组装
# https://www.zhihu.com/question/459266316/answer/1884583110
```


- 质控
    - fastp
- 群落分析
   - MetaPhlAn
   - MP <https://bioconductor.org/packages/release/bioc/vignettes/MicrobiotaProcess/inst/doc/MicrobiotaProcess.html#bridges-other-tools>


```{r}
fun <- function() {
  files <- list.files("~/outline/lixiao/published_data/ProteinMetabolBenson2023/", ".xlsx$", full.names = T)
  names(files) <- gs(files, ".*mmc([0-9]+).*", "\\1")
  files <- files[ order(as.numeric(names(files))) ]
  print(files)
  lapply(files, function(x) try(fxlsx(x), T))
}
m <- fun()

## use 7
saveRDS(m0, "~/outline/lixiao/published_data/ProteinMetabolBenson2023_mmc5.rds")
filter(m0, grpl(Metabolite_Name, "AMP", T), Target_Gene == "AREG")

m1 <- tibble::as_tibble(dplyr::select(m0, Target_Gene, Metabolite_Name, META_Rho, META_Q, META_P))
m1 <- dplyr::mutate(m1, .id = tolower(Metabolite_Name))
metas <- dplyr::mutate(metas, .id = tolower(name))
m1 <- map(m1, ".id", metas, ".id", "cid", col = "pubchem_cid")
m1 <- dplyr::select(m1, -.id)
m1 <- dplyr::mutate(m1, pubchem_cid = as.integer(pubchem_cid))
saveRDS(m1, "~/outline/lixiao/published_data/ProteinMetabolBenson2023_mmc5_small.rds")

m1$pubchem_cid %>% is.na %>% table
filter(m1, is.na(pubchem_cid))
metas$.id

unique(m1$.id) %>% .[!. %in% metas$.id]

m0 <- openxlsx2::read_xlsx("~/outline/lixiao/published_data/ProteinMetabolBenson2023/S4.xlsb")
m0 <- tibble::as_tibble(m0)
dat <- RCurl::getURL("https://mbenson.shinyapps.io/protein-metabolite/")

link <- start_drive()
link$open()
link$navigate("https://mbenson.shinyapps.io/protein-metabolite/")

fun_format <- function() get_table.html(link$getPageSource()[[1]])

meta1 <- fun_format()
meta2 <- fun_format()
meta3 <- fun_format()
meta4 <- fun_format()

metas <- lapply(list(meta1, meta2, meta3, meta4),
  function(x) as_tibble(select(x[[1]], name = 3, cid = 4))
)
metas <- frbind(metas)
metas <- dplyr::distinct(metas)
metas

m <- link$getPageSource()
m <- get_table.html(m[[1]])
```


