---
---

```{r include = F, eval = F}
info <- items(start = td("2024-03-28"), end = td("2025-03-18"), finish = td("2025-03-18"),
  id = "BSJF211201", client = "陶磊磊", inst = "",
  type = "补充分析",
  title = "分子对接二氢杨梅素与ATF4",
  save = ".items_supp.rds"
)
show.ic(info)

order_publish.bosai("supp.Rmd", "supp_out.Rmd")
idname <- formatName.bosai("./supp_out.docx")
order_packaging("./supp_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

## AutoDock vina 分子对接 (DHM)

`r snap(vn.dhm, 0:7)`

`r ref("DHM-All-combining-Affinity-data")`
`r ref("DHM-Overall-combining-Affinity")`
`r ref("Docking-161557-into-P18848")`
`r ref("Docking-161557-into-P18848-detail")`
<!-- LEGEND_END -->

```{r}
vn.dhm <- job_vina(c(dihydromyricetin = 161557), "ATF4")
#' @meth {get_meth(vn.dhm)}
vn.dhm <- step1(vn.dhm, FALSE)
vn.dhm <- step2(vn.dhm)
vn.dhm <- step3(vn.dhm, forceAF = TRUE)
vn.dhm <- step4(vn.dhm)
vn.dhm <- step5(vn.dhm)
vn.dhm@tables$step5$res_dock
vn.dhm@plots$step5$p.res_vina
vn.dhm <- step6(vn.dhm)
vn.dhm@plots$step6$Top1_161557_into_P18848
vn.dhm <- step7(vn.dhm)
vn.dhm@plots$step7$Top1_161557_into_P18848
```


```{r eval = T, echo = F, results = "asis"}
#| DHM-All-combining-Affinity-data
autor(vn.dhm@tables$step5$res_dock)
```


```{r eval = T, echo = F, results = "asis"}
#| DHM-Overall-combining-Affinity
autor(vn.dhm@plots$step5$p.res_vina)
```


```{r eval = T, echo = F, results = "asis"}
#| Docking-161557-into-P18848
autor(vn.dhm@plots$step6$Top1_161557_into_P18848)
```


```{r eval = T, echo = F, results = "asis"}
#| Docking-161557-into-P18848-detail
autor(vn.dhm@plots$step7$Top1_161557_into_P18848)
```

