---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(05), eval = ic())
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

联合三维基因组测序与单细胞测序技术解析先心病功能机制并建立分子学鉴别诊断方案

客户方案中要求的测序数据过多，可以调整的话，将根据分值要求和实际数据库可得的测序数据 (先天心脏病) 删减调整。 
预计可以使用的数据有：WGS 或 WES，RNA-seq, scRNA-seq, 等 (将从公共开源数据库获取)。
此外，如果客户提供数据，请对数据做简要说明，样品信息、分组等。5 月 9 日的那批数据，我猜测是 RNA-seq，但需要请客户明确。

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}


