---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(2), eval = ic(0, 0, 0, 0, 1))

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

列线图模型的建立与验证进行分析, 并按参考文献2描述所使用的统计方法

- 自发性蛛网膜下腔出血
    - 预后良好组
    - 预后不良组

结果见 \@ref(res)

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}


```{r}
fun_read <- function() {
  file <- "./order_material/原始数据/20230815-04 原始数据.xlsx"
  sheets <- openxlsx::getSheetNames(file)
  data <- lapply(1:2, function(x) fxlsx(file, sheet = x))
  names(data) <- sheets[1:2]
  frbind(data, idcol = "Group")
}
Raw <- fun_read()

```

## 预处理表格

```{r eval = T, echo = F, results = "asis"}
#| Formatted-data
autor(dat)
```

```{r}
vars <- c("WFNS分级", "迟发性脑缺血", "肺部感染", "颅内出血")

dat <- dplyr::select(Raw, Group, dplyr::all_of(vars))
dat <- dplyr::filter(dat, !is.na(`WFNS分级`))
dat <- dplyr::mutate(dat, Group = gs(Group, "[组]? .*$", ""),
  dplyr::across(dplyr::starts_with("WFNS"),
    function(x) dplyr::recode(x, '1' = 'I 级', '2' = 'II 级', '3' = 'III 级', '4' = 'IV 级', '5' = 'V 级')),
  dplyr::across(c(`迟发性脑缺血`, `肺部感染`, `颅内出血`), function(x) dplyr::recode(x, '0' = "无", '1' = "有") )
)
dat <- dplyr::mutate_all(dat, as.factor)
dat

```

## 结果 {#res}

```{r eval = T, echo = F, results = "asis"}
autor(lrm.eff$fit)
```

```{r eval = T, echo = F, results = "asis"}
#| eff-Nomogram-plot
autor(wrap(nomo.eff$p.nomo, 7, 4.5))
```

```{r eval = T, echo = F, results = "asis"}
#| eff-Bootstrap-calibration
autor(lrm.eff$p.cal)
```

```{r eval = T, echo = F, results = "asis"}
#| eff-Bootstrap-others
autor(lrm.eff$boots$lich)
```

```{r eval = T, echo = F, results = "asis"}
#| eff-ROC
autor(lrm.eff$roc$p.roc)
```

```{r eval = T, echo = F, results = "asis"}
#| eff-ROC-others
autor(lrm.eff$roc$lich)
```

```{r eval = T, echo = F, results = "asis"}
#| eff-ROC-data
autor(lrm.eff$roc$data)
```

```{r}
lrm.eff <- new_lrm(dat, "Group", rev.level = T, cn.mode = "1-")
nomo.eff <- new_nomo(lrm.eff, fun_at = seq(.1, 1, by = .2))
nomo.eff$p.nomo

```

```{r}
browseURL("./order_material/附件/02_低级别动脉瘤性蛛网膜下腔出血术后短期临床预后影响因素分析及预测模型构建.pdf")
```

