---
---

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

# 前言 {#introduction}

# 研究设计流程图 {#route}

```{r}
#| route
route <- as_network(
  list("RNA_seq_data:Preprocess",
    ), "tree"
)
p.route <- flowChart(route, 1.1, 1)
```

```{r, eval = T, echo = F, fig.width = 10, fig.height = 7, fig.cap = NULL}
p.route
```

# 材料和方法 {#methods}

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## ST 数据预处理

```{r}
#| pre
dirs <- list.files("/media/echo/6E3CE3153CE2D75D/曹卓测序结果/空间转录组/肺癌空间转录组测序/CellRanger/", full.names = T)

pbapply::pblapply(dirs,
  function(dir) {
    file <- list.files(dir, "tar\\.gz$", full.names = T)
    untar(file, exdir = dir)
  })
metadata <- tibble::tibble(dirs = dirs, target = paste0(dirs, "/outs"), sample = get_filename(dirs))
```

```{r}
## seurat
st <- job_seuratSp(metadata$target[[1]])
st <- step1(st)
st <- step2(st, 2500, 9000)
st <- step3(st, 1:15, 2)
st <- step4(st)

wrap(st@plots$step4$p.map_SingleR, 7, 5)

st <- step5(st, 5)
st <- step6(st, "Lung")

st@plots$step6$p.map_scsa

st@plots$step3$p.spatial_cluster
st@tables$step6$scsa_res
vis(st)

options(step_check = F)
```

## 细胞注释

### 富集分析

```{r}
#| enrichment
en <- asjob_enrich(st, "macroph|plasma|fibro|monocyte")
en <- step1(en)
```

### SCSA 注释

## 依据变异拷贝数鉴定肿瘤细胞

### copyKAT 解析肿瘤细胞

copyKAT [@DelineatingCopGaoR2021]

非整倍体是人类肿瘤细胞中最普遍的特征，约 90% 的肿瘤的基因组是非整倍体，而正常细胞是二倍体[@CausesAndConsGordon2012]

```{r}
#| copyKAT-all-cells
ka0 <- job_kat(st)
ka0 <- step1(ka0)
ka0 <- step2(ka0)
ka0 <- clear(ka0)
ka0@plots$step2$p.copykat

st <- map(st, ka0)
vis(st, "copykat_cell")
vis(st, "scsa_cell")
vis(st, "scsa_copykat")
```

### 肿瘤细胞重聚类

```{r}
st_cancer <- getsub(st, cells = grep("Cancer", object(st)@meta.data$copykat_cell))
vis(st_cancer)

st_cancer@step <- 2L
st_cancer <- step3(st_cancer, 1:15, 2)
vis(st_cancer, "seurat_clusters", 1.5)
```

## 拟时分析肿瘤细胞

### 构建拟时轨迹

### 根据拟时分析区分肿瘤细胞亚类

```{r}
#| monocle3
mn <- asjob_monocle(st_cancer, "seurat_clusters")
mn <- step1(mn, pt.size = 1.5)
mn@plots$step1$p.traj
mn@plots$step1$p.prin

mn <- step2(mn, "Y_7")
mn@plots$step2$p.pseu
mn <- step3(mn)
mn@plots$step3$gene_module_heatdata

    # mn$cellClass_tree.gene_module <- hclust(dist(t(mn@tables$step3$gene_module$graph_test.sig$aggregate)))
st_cancer.re <- regroup(st_cancer, mn@params$cellClass_tree.gene_module, 3,
  rename = list("3" = "cancer_1", "2" = "cancer_3", "1" = "cancer_2"))
vis(st_cancer.re, "regroup.hclust", 1.5)

p.ka_map <- vis(regroup(st_cancer, ka0, 15), "regroup.hclust", 1.5)
```

### 肿瘤细胞亚类差异分析和富集分析

```{r}
#| enrichment
st_cancer.re@step <- 4L
st_cancer.re <- step5(st_cancer.re)
st_cancer.re@tables$step5$all_markers

en.re <- asjob_enrich(st_cancer.re, NULL)
en.re <- step1(en.re)
en.re@tables$step1$res.kegg
en.re@plots$step1$p.kegg[[2]]
en.re@plots$step1$p.kegg[[3]]
```

```{r}
# sig
save.image("./sig.RData")

load("./sig.RData")
```

## 肿瘤细胞来源分析

### 肿瘤与上皮细胞或基底细胞差异分析

```{r}
st_epi <- getsub(st, cells = grep("Cancer|Basal|Epithe", object(st)@meta.data$scsa_copykat))
vis(st_epi, "scsa_copykat")

st_epi <- map(st_epi, st_cancer.re, "scsa_copykat", "regroup.hclust", "cancer_mapped")
vis(st_epi, "cancer_mapped")

st_epi <- diff(st_epi, "cancer_mapped",
  expand.grid(paste0("cancer_", 1:3), c("Basal cell", "Epithelial cell")))
```

```{r}
en.epi <- asjob_enrich(st_epi, NULL)
en.epi <- step1(en.epi)
en.epi@plots$step1$p.kegg[[1]]
```

## 细胞通讯

### 所有细胞之间的通讯

```{r}
st <- map(st, st_epi, "scsa_copykat", "cancer_mapped", "cancer_mapped")
vis(st, "cancer_mapped")
```

```{r}
cc <- asjob_cellchat(getsub(st, features = st@tables$step5$all_markers$gene), "cancer_mapped")
cc <- step1(cc)
cc <- step2(cc)
cc <- step3(cc)
cc <- step4(cc)
```


