---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{tikz}
  \usepackage{auto-pst-pdf}
  \usepackage{pgfornament}
  \usepackage{pstricks-add}
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(06), eval = ic(), lock = T, id = "重新组图")
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 主图 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

```{r}
fig1 <- cls(
  # rw(),
  cl("./Figure+Table/SCSA-annotation.pdf",
    "./Figure+Table/copykat_heatmap.png"),
  cl("./Figure+Table/cell-mapped-of-copyKAT-prediction.pdf")
)
fig1 <- render(fig1)
fig1
```

```{r eval = T, echo = F, results = "asis"}
#| MAIN-Fig-1
autor(fig1)
```

```{r}
fig2 <- cls(
    "./Figure+Table/re-classify-of-cancer-cells.pdf",
    rw("./Figure+Table/gene-module-of-co-expression-analysis.pdf", "./Figure+Table/pseudotime-add.pdf"),
    "./Figure+Table/cancer-cells-subtypes.pdf"
)
fig2 <- render(fig2)
fig2
```

```{r eval = T, echo = F, results = "asis"}
#| MAIN-Fig-2
autor(fig2)
```


```{r}
fig3 <- cls(
  # rw(),
  "./Figure+Table/cancer-cells-in-epithelial--or-basal-cells.pdf",
    "./Figure+Table/enrichment-of-markers-of-cancer-2-cells.pdf",
    "./Figure+Table/enrichment-of-markers-of-cancer-3-cells.pdf"
)
fig3 <- render(fig3)
fig3
```

```{r eval = T, echo = F, results = "asis"}
#| MAIN-Fig-3
autor(fig3)
```

```{r}
fig4 <- cls(
  # rw(),
  cl("./Figure+Table/cell-communication-heatmap.pdf"),
  cl("./Figure+Table/visualization-of-communication-between-macrophage-and-cancer-cells.pdf",
    "./Figure+Table/hsa04151.pathview.png"),
  cl("./Figure+Table/selected-pseudo-genes.pdf")
)
fig4 <- render(fig4)
fig4
```

```{r eval = T, echo = F, results = "asis"}
#| MAIN-Fig-4
autor(fig4)
```

```{r}
tiffs <- generate_tiffs()
```

```{r eval = T, echo = F, results = "asis"}
#| Tiff-figures
autor(tiffs)
```


# 附图  (可选) 

```{r eval = T, echo = F, results = "asis"}
autor("./Figure+Table/spatial-sample-QC.pdf")
```

```{r eval = T, echo = F, results = "asis"}
autor("./Figure+Table/PCA-ranking.pdf")
```

```{r eval = T, echo = F, results = "asis"}
autor("./Figure+Table/overview-of-cells-communication.pdf")
```

```{r eval = T, echo = F, results = "asis"}
autor("./Figure+Table/all-cells-communication-significance.pdf")
```

