---
---

```{r include = F, eval = F}
info <- items(start = td("2024-09-27"), end = td("2025-12-27"), finish = td("2024-12-26"),
  id = "BSXN240936", client = "李扬", inst = "中国医科大学附属盛京医院",
  type = "生信协助",
  title = "高级别浆液性卵巢癌",
  save = ".items_support.rds"
)
show.ic(info)

order_publish.bosai("support.Rmd", "support_out.Rmd")
idname <- formatName.bosai("./support_out.docx")
order_packaging("./support_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}



# 总结 {#conclusion}

