---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(05), eval = ic(3, 2, 1, 1, 0))
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"),
  di("自发性脑出血", "intracerebral hemorrhage", "ICH"),
  di("小胶质细胞代谢"),
  di("星形细胞胶质瘢痕")
)

# DEGs: Differential Expressed Genes 差异表达基因
# ICH: intracerebral hemorrhage 自发性脑出血
# MM: microglial metabolism 小胶质细胞代谢
# AS: astrocytic scar 星形细胞胶质瘢痕
```

自发性脑出血（ICH）（人或动物）后调控 小胶质细胞代谢 的关键基因XXX，并且该基因可能也调控 星形细胞胶质瘢痕生成。

客户马力前期发表的文章有做过盐诱导激酶 2（SIK-2）这个分子（PMID: 29018127），所以分析的时候可以看看XXX是否可以是SIK-2，或者XXX能否富集在SIK-2相关通路或其他分子机制上

数据库分析或测序筛选脑出血后调控小胶质细胞代谢的关键基因XXX


# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
geo <- job_geo("GSE227033")
geo <- step1(geo)
geo@params$guess
geo <- step2(geo)
untar("./GSE227033/GSE227033_RAW.tar", exdir = "./GSE227033")
lapply(list.files("./GSE227033/", "cloupe|filtered", full.names = T), file.remove)

prepare_10x("./GSE227033/GSM7090268_C1.expression.txt.gz", single = T, col.gene = 2:1)
prepare_10x("./GSE227033/GSM7090269_C2.expression.txt.gz", single = T, col.gene = 2:1)
prepare_10x("./GSE227033/GSM7090270_M1.expression.txt.gz", single = T, col.gene = 2:1)
prepare_10x("./GSE227033/GSM7090271_M2.expression.txt.gz", single = T, col.gene = 2:1)
```

```{r}
# sr.ctrl <- job_seurat("./GSE227033/GSM7090268_C1")
# sr.ctrl <- step1(sr.ctrl)
# sr.ctrl@plots$step1$p.qc
# sr.ctrl <- step2(sr.ctrl, 1000, 9000)
```

```{r}
sr <- job_seuratn(
  c("./GSE227033/GSM7090268_C1", "./GSE227033/GSM7090269_C2",
    "./GSE227033/GSM7090270_M1", "./GSE227033/GSM7090271_M2"),
  c("Control_1", "Control_2", "Model_1", "Model_2"))
sr <- step1(sr, 1000, 9000)
sr <- step2(sr)
sr <- step3(sr, 1:15, 1.2)
sr <- step4(sr, "")
sr <- step5(sr)
sr <- step6(sr, "Brain", org = "M")
sr@plots$step6$p.map_scsa

```

```{r}
sr <- mutate(sr, group = strx(orig.ident, "[A-Za-z]+"),
  cellType_group = paste0(scsa_cell, "_", group))
p.srCellType <- wrap(vis(sr, "cellType_group"), 12, 6)
p.srCellType

sr <- diff(sr, "cellType_group", list(c("Microglial cell_Model", "Microglial cell_Control")), name = "micro")
sr@params$micro
```

```{r}
mn.mi <- do_monocle(sr, "Microglial")
mn.mi <- step1(mn.mi, "cellType_group", pre = T)
mn.mi@plots$step1$p.prin
mn.mi <- step2(mn.mi, "Y_9")
mn.mi@plots$step2$p.pseu
mn.mi <- step3(mn.mi)
mn.mi@tables$step3$graph_test.sig
mn.mi@plots$step3$gene_module_heatdata

```

```{r}
scf <- asjob_scfea(sr, meta(sr)$scsa_cell == "Microglial cell", "m")
scf <- set_remote(scf)
scf <- step1(scf)
scf <- step2(scf)
scf@plots$step2$p.loss

lm.scf <- asjob_limma(scf, meta(sr), "group")
lm.scf <- step1(lm.scf)
lm.scf <- step2(lm.scf, Model - Control, label = "name", cut.fc = .3)
lm.scf@plots$step2$p.valcano$`Model - Control`
lm.scf@tables$step2$tops$`Model - Control`
```

```{r}
Tops.flux <- lm.scf@tables$step2$tops$`Model - Control`
Tops.flux

belong.flux <- reframe_col(dplyr::select(Tops.flux, gene, name), "gene", function(x) unlist(x))
belong.flux <- dplyr::relocate(belong.flux, gene, Metabolic_flux = name)
belong.flux

genes.topFlux <- unique(unlist(Tops.flux$gene))
dplyr::filter(mn.mi@tables$step3$graph_test.sig, gene_id %in% genes.topFlux)
genes.topFlux
```

```{r}
bm <- job_biomart("mmu", F)
bm <- step1(bm, genes.topFlux, "mgi_symbol")
en.topflux <- job_enrich(genes.topFlux, bm$anno, "mgi_symbol")
en.topflux <- step1(en.topflux, "mmu", "org.Mm.eg.db")
en.topflux@plots$step1$p.kegg$ids
en.topflux@plots$step1$p.go$ids
```


```{r}
pb.SigFluxGene <- map(mn.mi, genes.topFlux, list(c("Y_9", "Y_19"), c("Y_9", "Y_5")),
  enrich = en.topflux, assay = "SCT",
  enrichExtra = belong.flux,
  HLs = list(Variable_features = Seurat::VariableFeatures(sr@object)),
  group_by = "Variable_features",
  split = NULL
)
wrap(pb.SigFluxGene, 13, 8)

genes.VarTopFlux <- intersect(genes.topFlux, Seurat::VariableFeatures(sr@object))
genes.VarTopFlux
```

```{r}
bm2.topFlux <- job_biomart2(genes.topFlux, "mmu", "hsa")
bm2.topFlux <- step1(bm2.topFlux)
bm2.topFlux@params$mapped
```


```{r}
bm2.sik <- job_biomart2("SIK2", "hsa", "mmu")
bm2.sik <- step1(bm2.sik)
bm2.sik@params$mapped

dplyr::filter(mn.mi@tables$step3$graph_test.sig, gene_id == "Sik2")
dplyr::filter(sr@params$micro, gene == "Sik2")
```

```{r}
sdb.topFlux <- job_stringdb(bm2.topFlux@params$mapped$hgnc_symbol)
sdb.topFlux <- step1(sdb.topFlux)
sdb.topFlux <- readRDS("./sdb.rds")
sdb.topFlux@plots$step1$p.mcc

fun_human <- function(x) {
  bm2.topFlux$mapped$hgnc_symbol[ match(bm2.topFlux$mapped$mgi_symbol, x) ]
}
ppi.topFlux <- filter(sdb.topFlux, fun_human(genes.VarTopFlux), fun_human(genes.topFlux),
  arrow = F, label.shape = c("Variable feature", "Others")
)
ppi.topFlux$p.mcc
```


