---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(1), coef = NA)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

- 三七总皂苷 panax notoginseng saponins 中有效成分
- 结合疾病骨折愈合（软骨内骨化，血管生成）做网络药理学分析
- 候选基因的功能通路富集分析
- 分子对接，与piezo1 (如果Mandenol与piezo1)
    - 分子对接见 Fig. \@ref(fig:Overall-combining-Affinity)

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))
```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 分子对接

```{r eval = T, echo = F, results = "asis"}
#| Overall-combining-Affinity
autor(wrap(vn@plots$step5$p.res_vina, 7.2, 1.5))
```

```{r eval = T, echo = F, results = "asis"}
#| Mandenol-combine-PIEZO1
autor(.file_fig("./figs/5282184_into_piezo1.png"))
```

```{r}
vn <- job_vina(c(Mandenol = 5282184), "PIEZO1")
vn <- step1(vn, NULL)
# https://alphafold.ebi.ac.uk/entry/H7C2J5
vn <- step2(vn)
file.copy("./order_material/piezo1.pdb", "./protein_pdb/piezo1.pdb")
vn <- step3(vn, extra_pdb.files = c(piezo1 = "./protein_pdb/piezo1.pdb"), extra_layouts = nl(5282184, "piezo1"))
vn <- step4(vn)
vn <- step5(vn)
wrap(vn@plots$step5$p.res_vina, 7.2, 1.5)
vn <- step6(vn)
vn <- step7(vn)
```


