
## NCBI GEO

### Sepsis lung injury

```{r}
ge <- job_geo("GSE165226")
ge <- step1(ge)
ge@params$guess

metadata <- dplyr::mutate(ge@params$guess,
  group = ifelse(grpl(title, "control"), "Control", "Model"),
  sample = rownames
)

lm <- asjob_limma(ge, metadata)
```

```{r}
# PharmGKB
x <- ftibble("~/outline/lixiao/database/PharmGKB_genes.tsv.gz")
y <- ftibble("~/outline/lixiao/database/PharmGKB_phenotypes.tsv.gz")

z <- ftibble("~/outline/lixiao/database/PharmGKB_relationships.tsv.gz")
z <- dplyr::filter(z, (Entity1_type == "Gene" & Entity2_type == "Disease") |
  (Entity2_type == "Gene" & Entity1_type == "Disease"))

fun_format <- function(x) {
  n <- 0L
  split_lapply_rbind(x, ~ Entity1_type,
    function(x) {
      n <<- n + 1L
      if (n == 2L) {
        colnames(x) <- colnames(x)[c(4:6, 1:3, 7:ncol(x))]
      }
      return(x)
    })
}
x <- fun_format(z)

```


```{r}
# DisGeNet
x <- ftibble("~/outline/lixiao/database/DisGeNet_disease_associations.tsv.gz")

y <- RCurl::getURL('https://www.disgenet.org/browser/0/1/0/C0000768/0/2000/source__ALL/_b./#')
tt <- as_tibble(get_table.html(y)[[1]])
tt <- as_tibble(get_table.html(y)[[2]])

fun_format <- function(x) {
  x <- dplyr::select(x, type = 1, value = 2)
  x <- dplyr::mutate(x, type = gs(type, "^(.+?):.*", "\\1"),
    type = ifelse(grpl(type, "^[A-Z]"), type, "UniProt"),
    type = make.names(type))
  rows <- nrow(x) / 3
  x <- split_lapply_rbind(x, rep(1:rows, each = 3),
    function(x) {
      tidyr::spread(x, type, value)
    })
  x
}

fun_format(tt)

apply(tt, 1, function(x) any(grpl(x, "score", T)))
```


### `r d("sli")`

```{r eval = T, echo = F, results = "asis"}
#| SLI-Overall-targets-number-of-datasets
autor(gm.sli@plots$step2$p.cols)
```

```{r}
gm.sli <- job_gmix("Septic lung injury", "lung injury")
gm.sli <- step1(gm.sli)
gm.sli <- step2(gm.sli, NULL, 3, 5)
gm.sli@plots$step2$p.cols
gm.sli$lst.genes
```

```{r}
db_c2 <- get_c2_data("Glycolysis", mode = "mmu")

bm <- job_biomart("hsa")
bm <- step1(bm, unlist(db_c2, use.names = F), "entrezgene_id")
bm$anno
```

```{r eval = T, echo = F, results = "asis"}
#| Glycolysis-Genes-annotation
autor(bm$anno)
```

从 MSigDB 筛选`r d("g")` 相关基因。


客户需求：希望把生信的可视化结果弄得漂亮一点，目前PPI图虽然可以看出kif2c和myc的关系，但是过于单调。有没有可能再加分子对接或者两者在糖酵解代谢途径中的富集等等（不知道kegg和go分析能否用上）。辛苦增加部分生信分析的图片和结果（就是想视觉上再丰富一点，图做得好看一点多一点）
