---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
output:
  custom_docx_document2:
    reference_docx: '`r system.file("extdata", "bosai.docx", package = "utils.tool")`'
---


```{r include = F, eval = F}
info <- items(start = td("2025-02-27"), end = td("2025-03-10"), finish = td(NA),
  id = "BSXG250226", client = "公司内部", inst = "",
  type = "思路设计",
  title = "小鼠结肠炎的单细胞测序数据",
  save = ".items_idea.rds"
)
show.ic(info)

order_publish.bosai("idea.Rmd", "idea_out.Rmd")
formatName.bosai("./idea_out.docx")
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"), autor_asis = F)
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 研究背景 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("结肠炎:")
)
# DEG: Differentially expressed genes 差异表达基因
# C: colitis 结肠炎

```

## 思路 {#introduction}

# 可行性 {#methods}

# 创新性 {#results}

# GEO 检索方法

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 参考文献和数据集 {#workflow}

## GSE 数据搜索 (COLITIS_SINGLE_CELL)

`r snap(gds.colitis_single_cell, 0:3)`
`r snap(gds.colitis_single_cell, "a")`

```{r}
gds.colitis_single_cell <- job_gds(
  c("colitis", "single cell"), n = 3:20, org = "Mus musculus"
)
gds.colitis_single_cell <- step1(
  gds.colitis_single_cell, grpl(gdsType, "high throughput sequencing"), 
  single_cell = NULL, clinical = NULL, rna_or_array = NULL,
  extras = "cancer|treatment|single.nuclei|interferons|microbiota"
)
vis(gds.colitis_single_cell)
active(gds.colitis_single_cell, which = 1:12)

#' @meth {get_meth(gds.colitis_single_cell)}
gds.colitis_single_cell <- step2(gds.colitis_single_cell)
gds.colitis_single_cell <- expect(gds.colitis_single_cell, geo_cols())
gds.colitis_single_cell <- anno(gds.colitis_single_cell)
# GSE264408
```

## GSE 数据搜索 (COLITIS)

`r snap(gds.colitis, 0:3)`
`r snap(gds.colitis, "a")`

```{r}
gds.colitis <- job_gds(c("colitis"), org = "Mus musculus")
gds.colitis <- step1(
  gds.colitis,
  extras = "cancer|treatment|single.nuclei|single.cell|interferons|microbiota|treated|Inhibit"
)
#' @meth {get_meth(gds.colitis)}
gds.colitis <- step2(gds.colitis)
gds.colitis <- step3(gds.colitis, ref = gds.colitis$excludes, not = TRUE)
gds.colitis <- expect(gds.colitis, geo_cols())
gds.colitis <- anno(gds.colitis)
vis(gds.colitis)
active(gds.colitis)
```


