---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \definecolor{shadecolor}{RGB}{242,242,242}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
---


```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover("补肾健脾汤网络药理学分析")
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

补肾健脾汤网络药理学 (党参9 g、白术12 g、茯苓12 g、甘草6 g、山药12 g、泽泻9 g、地黄12 g、山茱萸9 g、牡丹皮9 g、黄芪12 g，补骨脂9 g，杜仲9 g)，绘制药方-草药-主要活性成分-靶点图。

结果见 Fig. \@ref(fig:Herbs-compounds-and-targets)

# 材料和方法 {#methods}

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 补肾健脾汤网络药理学分析

### 成分

```{r}
hb <- job_herb(c("党参", "白术", "茯苓", "甘草", "山药", "泽泻", "地黄", "山茱萸", "牡丹皮", "黄芪", "补骨脂", "杜仲"))
hb <- step1(hb)
hb <- step2(hb, 100)
hb <- step3(hb)
```

```{r eval = T, echo = F, results = "asis"}
#| Herbs-information
autor(hb@params$herbs_info)
```

```{r eval = T, echo = F, results = "asis"}
#| Components-of-Herbs
autor(hb@tables$step1$herbs_compounds, key = "Ingredient.name")
```

```{r eval = T, echo = F, results = "asis"}
#| intersection-of-all-compounds
autor(wrap(hb@plots$step3$p.herbs_compounds, 12))
```

### 成分靶点

```{r eval = T, echo = F, results = "asis"}
#| tables-of-Herbs-compounds-and-targets
autor(hb@params$easyRead)
```

```{r eval = T, echo = F, results = "asis"}
#| Herbs-compounds-and-targets
autor("./Figure+Table/Herbs-compounds-and-targets.png")
```

```{r}
data.allu <- select(hb@params$easyRead, Herb_pinyin_name, Ingredient.name, Target.name)
data.allu <- filter(data.allu, !is.na(Target.name))
p.allu <- new_allu(data.allu, axes = 1:3, label.auto = T, label.freq = 200)
wrap(p.allu, 15, 12)
p.allu

pdf_convert("./Figure+Table/Herbs-compounds-and-targets.pdf", filenames = "./Figure+Table/Herbs-compounds-and-targets.png", dpi = 300)
```


