

```{r}
og <- job_ogwas("stones")
og@step <- 0L
og <- step1(og, "ieu-a-298")
```


## genes (GWAS) and Metabolites

<https://pubmed.ncbi.nlm.nih.gov/?term=gallstones%2016s&filter=datesearch.y_10>

Metagenomics of pigmented and cholesterol gallstones: the putative role of bacteria
<https://trace.ncbi.nlm.nih.gov/Traces/?view=study&acc=SRP136827>

Carrying asymptomatic gallstones is not associated with changes in intestinal
microbiota composition and diversity but cholecystectomy with significant
dysbiosis
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7988160/>

[@InteractionsBeKeren2015]
Interactions between the intestinal microbiota and bile acids in gallstones patients

Biliary Microbiota and Bile Acid Composition in Cholelithiasis
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7352139/>
16s RNA seq
<https://www.ebi.ac.uk/ena/browser/view/PRJEB12755>

Patients with Primary and Secondary Bile Duct Stones Harbor Distinct Biliary
Microbial Composition and Metabolic Potential
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9082501/>
16s 
<https://www.ncbi.nlm.nih.gov/bioproject/PRJNA580086/>





Mendelian randomization analyses support causal relationships between blood
metabolites and the gut microbiome
[@MendelianRandoLiuX2022]

## Gallstones genes metabolites

## GWAS (SNP) and metabolites

An atlas of genetic influences on human blood metabolites
<https://pubmed.ncbi.nlm.nih.gov/24816252/>

### Human

Biliary Microbial Structure of Gallstone Patients With a History of Endoscopic Sphincterotomy Surgery
16s
bile microbiome
<https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7873689/>


