---
---

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
deparse_mail()
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

见分析流程 \@ref(workflow)

# 附：分析流程 {#workflow}

## TCGA 差异分析

### 癌旁组织和癌组织的差异分析

```{r eval = T, echo = F, results = "asis"}
#| DEGs-of-HNSC
autor(lm@plots$step2$p.valcano[[1]])
```

```{r eval = T, echo = F, results = "asis"}
#| tables-of-DEGs-of-HNSC
autor(select(lm@tables$step2$tops[[1]], -(1:11), -(13:15)))
```

```{r}
tc <- job_tcga("TCGA-HNSC")
tc <- step1(tc)
tc <- step2(tc)
tc <- step3(tc)

clear(tc)
lm <- asjob_limma(tc)
lm@params$p.isTumor
lm@object$samples %<>% dplyr::mutate(group = isTumor)
clear(lm)

lm <- step1(lm)
lm <- step2(lm, tumor - normal)
lm@params$normed_data$targets

lm@plots$step2$p.valcano[[1]]
lm@tables$step2$tops[[1]]

clear(lm)
```

## 关联分析

使用 Top 100 的 DEGs 对乙酰酶对应的基因分析关联性。

```{r eval = T, echo = F, results = "asis"}
#| Correlation-heatmap
autor(p.cor)
```

```{r eval = T, echo = F, results = "asis"}
#| tables-of-Correlation-results
autor(as_tibble(corp))
```

```{r}
top100 <- tops
tops <- head(lm@tables$step2$tops[[1]], n = 100)
tops
```

```{r}
data_coa <- fxlsx("./order_material/coa_protein.xlsx", colNames = F)
sep_coa <- c(grp(data_coa$X1, "^[^a-zA-Z]"), nrow(data_coa))
coa <- lapply(1:length(sep_coa[-1]),
  function(n) {
    x <- data_coa$X1
    x <- x[ sep_coa[n]:sep_coa[n + 1] ]
    x[grp(x, "^[a-zA-Z]")]
  })
names(coa) <- c("histone acetyltransferase", "Histone deacetylase")
```

```{r}
data <- as_tibble(lm@params$normed_data$E)
data <- map(data, "rownames", lm@params$normed_data$genes, "gene_id", "gene_name")
data <- dplyr::mutate(data, gene_name = gname(gene_name))
data.sub <- dplyr::filter(data, gene_name %in% dplyr::all_of(unlist(coa)))

data.tops <- dplyr::filter(data, gene_name %in% dplyr::all_of(gname(tops$gene_name)))
data.tops <- dplyr::distinct(data.tops, gene_name, .keep_all = T)

corp <- cal_corp(data.sub, data.tops, "CoA", "Tops", trans = T)

hp <- new_heatdata(corp)
hp <- callheatmap(hp)
p.cor <- wrap(hp, 25, 7)

sig.corp <- filter(corp, sign != "-")
```

## 以 STRINGdb 筛选乙酰酶和蛋白的结合

以上述显著关联的基因 (P < 0.05) 和乙酰酶对应的蛋白构建互作网络 (STRINGdb 构建 PPI)，提取乙酰酶的作用关系。

```{r eval = T, echo = F, results = "asis"}
#| CoA-enzyme-interact-with-the-proteins
autor(p.allu)
```

以下为上述分析使用的乙酰酶：

```{r eval = T, echo = F, results = "asis"}
#| CoA
autor(new_lich(coa))
```

```{r}
str <- asjob_stringdb(rm.no(c(sig.corp$CoA, sig.corp$Tops)))
str <- step1(str)

coaAll <- unlist(coa, use.names = F)

binds <- dplyr::select(str@params$edges, from, to)
fun <- function(data, ref) {
  cols <- colnames(data)
  data <- apply(data, 1, simplify = F,
    function(x) {
      if (!all(x %in% ref))
        unique(c(x[x %in% ref], x))[1:2]
    })
  data <- lst_clear0(data)
  data <- data.frame(from = vapply(data, function(x) x[1], character(1)),
    to = vapply(data, function(x) x[2], character(1)))
  data <- dplyr::filter(data, from %in% !!ref)
  dplyr::distinct(data)
}
binds <- fun(binds, coaAll)
binds$group <- ifelse(binds$from %in% coa[[1]], "acetyltransferase", "deacetylase")
colnames(binds)[1:2] <- c("Enzyme", "Binding Protein")

p.allu <- new_allu(binds, 3)
```

## CREBBP 在 TCGA 数据集中的表达

CREBBP 为非差异表达基因。

```{r eval = T, echo = F, results = "asis"}
#| CREBBP-in-TCGA-dataset
autor(p.crebbp)
```

```{r}
save_small()

tc <- readRDS("./tc.3.rds")
lm <- readRDS("./lm2.rds")
load("./small.rdata")

lm@params$normed_data

p.crebbp <- map(lm, "CREBBP", "gene_name")
```


