---
title: Analysis
author: 'Huang LiChuang of Wie-Biotech'
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    toc: true
    toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \definecolor{shadecolor}{RGB}{242,242,242}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
---


```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
deparse_mail()
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

见分析流程 \@ref(workflow)

# 附：分析流程 {#workflow}

## TCGA 差异分析

### 癌旁组织和癌组织的差异分析

```{r eval = T, echo = F, results = "asis"}
#| DEGs-of-HNSC
autor(lm@plots$step2$p.valcano[[1]])
```

```{r eval = T, echo = F, results = "asis"}
#| tables-of-DEGs-of-HNSC
autor(select(lm@tables$step2$tops[[1]], -(1:11), -(13:15)))
```

```{r}
tc <- job_tcga("TCGA-HNSC")
tc <- step1(tc)
tc <- step2(tc)
tc <- step3(tc)

clear(tc)
lm <- asjob_limma(tc)
lm@params$p.isTumor
lm@object$samples %<>% dplyr::mutate(group = isTumor)
clear(lm)

lm <- step1(lm)
lm <- step2(lm, tumor - normal)
lm@params$normed_data$targets

lm@plots$step2$p.valcano[[1]]
lm@tables$step2$tops[[1]]

clear(lm)
```

## 关联分析

使用 Top 100 的 DEGs 对乙酰酶对应的基因分析关联性。

```{r eval = T, echo = F, results = "asis"}
#| Correlation-heatmap
autor(wrap(res.corp$hp, 25, 7))
```

```{r eval = T, echo = F, results = "asis"}
#| tables-of-Correlation-results
autor(as_tibble(res.corp$corp))
```

```{r}
top100 <- tops
tops <- head(lm@tables$step2$tops[[1]], n = 100)
tops
```

```{r}
data_coa <- fxlsx("./order_material/coa_protein.xlsx", colNames = F)
sep_coa <- c(grp(data_coa$X1, "^[^a-zA-Z]"), nrow(data_coa))
coa <- lapply(1:length(sep_coa[-1]),
  function(n) {
    x <- data_coa$X1
    x <- x[ sep_coa[n]:sep_coa[n + 1] ]
    x[grp(x, "^[a-zA-Z]")]
  })
names(coa) <- c("histone acetyltransferase", "Histone deacetylase")
```

```{r}
res.corp <- cal_corp(lm, NULL, unlist(coa), tops$gene_name, c("CoA", "Tops"))
```

## 以 catRapid 筛选乙酰酶和 RNA 的结合

详细结果可见于 catRapid 服务器： <http://service.tartaglialab.com/email_redir/757168/2e2b07eab4>

在这里，将所有结合可能 (蛋白结合RNA) 去重复后，按 Ranking 取前 30。

```{r eval = T, echo = F, results = "asis"}
#| CoA-enzyme-binding-with-candidate-RNA-top30
autor(cr@plots$step3$p.allu)
```

```{r eval = T, echo = F, results = "asis"}
#| tables-of-CoA-enzyme-binding-with-candidate-RNA-top30
autor(cr@tables$step3$dat.ref)
```

对表格的各列的解释请参考： <http://service.tartaglialab.com/static_files/shared/documentation_omics2.html>

```{r}
cr <- job_catr(coaAll, tops$gene_name)
cr <- step1(cr)
# http://service.tartaglialab.com/email_redir/757168/2e2b07eab4
cr <- step2(cr)
cr@plots$step2$p.upset
cr@tables$step2$top

cr <- step3(cr, top = 30, group = coa, label.auto = F)
cr@plots$step3$p.allu
cr@tables$step3$dat.ref

clear(cr)
```

以下为上述分析使用的乙酰酶：

```{r eval = T, echo = F, results = "asis"}
#| CoA
autor(new_lich(coa))
```

## CREBBP 在 TCGA 数据集中的表达

CREBBP 为非差异表达基因。

```{r eval = T, echo = F, results = "asis"}
#| CREBBP-in-TCGA-dataset
autor(p.crebbp)
```

```{r}
save_small()

tc <- readRDS("./tc.3.rds")
lm <- readRDS("./lm2.rds")
load("./small.rdata")

lm@params$normed_data

p.crebbp <- map(lm, "CREBBP", "gene_name")
```


