---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
output:
  custom_docx_document2:
    reference_docx: '`r system.file("extdata", "bosai.docx", package = "utils.tool")`'
---


```{r include = F, eval = F}
info <- items(start = td("2025-02-06"), end = td("2025-02-06"), finish = td("2025-02-07"),
  id = "BSXL231116", client = "千昌石", inst = "",
  type = "生信协助",
  title = "图片修改",
  save = ".items_support.rds"
)
show.ic(info)

order_publish.bosai("support.Rmd", "support_out.Rmd")
idname <- formatName.bosai("./support_out.docx")
order_packaging("./support_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

`r ref("Forest-plot")` 
`r ref("SsGSEA-score")` 

```{r}
dat_forest <- ftibble("./order_material/result/step2_coxph/gene.csv")
dat_forest <- dplyr::rename(dat_forest, HR_detail = `HR (95% CI for HR)`)
dat_forest <- dplyr::mutate(
  dat_forest, geneName = factor(
    geneName, c("PALLD", "FSTL1", "WISP1", "RAB31", "ADAMTS2")
  )
)
dat_forest <- dplyr::arrange(dat_forest, geneName)

test <- forestplot::forestplot(
  dat_forest, labeltext = c(geneName, p.value, HR_detail),
  mean = HR, lower = lower, upper = upper,
  graph.pos = 3, zero = 1, vertices = TRUE,
  hrzl_lines = .forest_lines(dat_forest),
  col = forestplot::fpColors(box = "darkred", lines = "darkred", summary = "darkred")
)
p.forest <- forestplot::fp_add_header(
  test, geneName = "Gene", p.value = "P value", HR_detail = "Hazard Ratio (95% CI)"
)
p.forest

p.forest <- set_lab_legend(p.forest, "forest plot", "forest plot")
p.forest
```

```{r}
dat_ssore <- ftibble("./order_material/result/step4_ssgsea/ssGSEA.csv")
dat_ssore <- tidyr::pivot_longer(dat_ssore, -(1:3), names_to = "cell", values_to = "score")
dat_ssore <- dplyr::mutate(dat_ssore, cell = factor(cell, unique(cell)))

dat_ssore_sig <- dplyr::group_by(dat_ssore, cell)
dat_ssore_sig <- dplyr::summarise(dat_ssore_sig, p.value = t.test(score ~ group)$p.value)
dat_ssore_sig <- dplyr::mutate(
  dat_ssore_sig, sign = ifelse(p.value < .05, "*", "ns")
)

p.box <- ggplot(dat_ssore) +
  geom_boxplot(aes(x = cell, y = score, fill = group)) +
  geom_text(data = dat_ssore_sig, aes(x = cell, y = .6, label = sign)) +
  theme_classic() +
  labs(x = "", y = "ssGSEA score", fill = "") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1), legend.position = "top")
p.box <- wrap(p.box, 7, 4.5)
p.box <- set_lab_legend(p.box, "ssGSEA score", "ssGSEA score")

p.box
```

```{r}
dat_wgcna <- ftibble("./order_material/result/step1_WGCNA/")
dat_wgcna

```

```{r}
dat_cor <- ftibble("./order_material/result/step1_WGCNA/")
dat_cor
```

```{r}
dat_lasso_test <- ftibble("./order_material/result/step3_multicox/test_data.csv")
dat_lasso_train <- ftibble("./order_material/result/step3_multicox/train_data.csv")
dat_lasso_train

set.seed(2022)
m <- glmnet::cv.glmnet(
  as.matrix(dplyr::select(dat_lasso_train, ADAMTS2:WISP1)),
  survival::Surv(dat_lasso_train$OS.time, event = dat_lasso_train$OS),
  family = "cox", alpha = 1, type.measure = "C", nfold = 10
)
plot(m)
rsvg::rsvg_pdf("./material/Lasso_cv_statistics.svg", "./material/Lasso_cv_statistics.pdf")
```


```{r eval = T, echo = F, results = "asis"}
#| Forest-plot
autor(wrap(p.forest))
```


```{r eval = T, echo = F, results = "asis"}
#| SsGSEA-score
autor(p.box)
```

# 总结 {#conclusion}

