---
---

```{r include = F, eval = F}
info <- items(start = td("2025-04-08"), end = td("2025-04-08"), finish = td(NA),
  id = "BS.develop", client = "", inst = "",
  type = "模块开发",
  title = "GEO 数据库检索和差异分析",
  note = "",
  save = ".items_module.rds"
)
show.ic(info)

order_publish.bosai("module.Rmd", "module_out.Rmd")
formatName.bosai("./module_out.docx")
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"), autor_asis = F)
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

```{r}
cdRun("git clone --depth 1 https://github.com/rstudio/shiny-examples")
if (!require('shiny')) {
  install.packages(c("shiny", "shinyjs"))
}
remotes::install_github('pvermees/IsoplotR')
remotes::install_github('pvermees/IsoplotRgui')
```

```{r}
shiny::runApp("./shiny-examples/test")
```

