---
---

```{r include = F}
deparse_mail()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic("DEGs", "Differential Expressed Genes", "差异表达基因")
```

寻找 circRNA6783 与 miR-770-5p 的结合靶点，miR-770-5p 与 VRK2 的结合靶点

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

```{r}
je <- job_esearch("circRNA-miRNA")
grpf(je@object$Title, "interaction", ignore.case = T)

filter(je@object, grpl(Title, "starBase"))

je.n <- job_esearch("circRNA-miRNA")
vis(je.n)

```

## circRNA 结合 miRNA

<https://github.com/annadalmolin/CRAFT>

## miRNA 结合 mRNA

### 使用的序列 (Fasta)

```{r eval = T, echo = F, results = "asis"}
autor("./miranda2023-12-14_17_34_38.593871/")
```

### 预测结果

```{r eval = T, echo = F, results = "asis"}
#| MiRNA-bind-mRNA-overview-of-all-candidates
autor(mi@plots$step2$p.overs)
```

```{r eval = T, echo = F, results = "asis"}
#| VRK2-Top-match
autor(mi@plots$step2$p.tops$VRK2)
```

```{r}
mi <- job_miranda("miR-770-5p", c("VRK2"))
sig(mi) <- "miRNA-bind-mRNA"
mi <- step1(mi)

mi@step <- 1L
mi <- step2(mi)
mi@plots$step2$p.tops     
mi@plots$step2$p.overs
```
