---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(4), eval = ic(0, 1, 0, 1, 0))
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

药对：白花蛇舌草，半枝莲，浙贝母
疾病：乳腺癌
目标：提供中药-有效成分-乳腺癌相关靶点的网药分析


# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 网络药理学

### 成分

```{r eval = T, echo = F, results = "asis"}
#| Herbs-information
autor(tc2@params$herbs_info)
```

```{r eval = T, echo = F, results = "asis"}
#| Compounds-filtered-by-OB-and-DL
autor(tc2@tables$step3$t.ob_dl_filtered)
```

```{r eval = T, echo = F, results = "asis"}
#| intersection-of-all-compounds
autor(wrap(tc2@plots$step3$p.herbs_compounds, 7, 5))
```

### 成分靶点

```{r eval = T, echo = F, results = "asis"}
#| tables-of-Herbs-compounds-and-targets
autor(tc2@params$easyRead)
```

```{r}
herbs <- c("白花蛇舌草", "半枝莲", "浙贝母")

tc2 <- job_tcmsp2(herbs)
tc2 <- step1(tc2)
tc2 <- step2(tc2)
tc2 <- step3(tc2)
tc2@tables$step3$t.ob_dl_filtered

```
