---
---

```{r include = F, eval = F}
deparse_mail()
# info <- items(belong = odate(05), eval = ic(2, 2, 0, 1, 0), lock = T)
info <- items(belong = odate(05), eval = ic(1, 2, 0, 0, 0), lock = T)
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

1. tRF-31 和 FUBP3 分子对接 (tRNA 与蛋白结合)
2. 生信分析预测 FUBP 3 下游 DNA （包括 FUBP3 蛋白与 LMNB2 的DNA序列之间的结合位点预测）

RNA-protein docking

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}


