---
---

```{r include = F, eval = F}
info <- items(start = td("2026-03-03"), end = td("2026-03-03"), finish = td("2026-03-03"),
  id = "", client = "", inst = "",
  type = "index",
  title = "",
  save = ".items_index.rds"
)
show.ic(info)

order_publish.complex("index.Rmd", "index_out.Rmd")
idname <- formatName.complex("./index_out.docx")
order_packaging("./index_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.complex(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}



# 总结 {#conclusion}

如何将 nvim 用于远程服务器？

Use local Nvim and Nvim configuration, but start R on a remote server to send code and analyze data.

我决定，在远程服务器中配置 nvim，通过 ssh 连接使用远程的 nvim。那么，能让本地最顺畅使用远程 nvim 的办法是什么？不会因为网络原因而受到卡顿。

考虑使用 Mosh 替代 SSH 是何种意思？具体而

远程没有sudo 权限能安装使用 mosh 吗？

github 上，如何用英文：感谢您的耐心和及时答复！

