---
---

```{r include = F, eval = F}
info <- items(start = td("20241030"), end = td("20241213"), finish = NA,
  id = "BSHQ240813", client = "王凯", inst = "大连医科大学附属第二医院",
  type = "生信分析",
  title = " CAP2通过靶向EMT信号通路促进黑色素瘤进展",
  save = ".items_analysis.rds"
)
show.ic(info)

order_publish.bosai("analysis.Rmd", "analysis_out.Rmd")
idname <- formatName.bosai("./analysis_out.docx")
order_packaging("./analysis_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

1. 通过生物信息分析分析 CAP2 在黑色素瘤异常表达且与预后相关。HPA数据库分析。
2. 为了研究CAP2影响黑色素瘤进展的机制，进行GSEA等生物信息分析，寻找与CAP2R显著相关的下游信号通路

```{r}
dic(di("差异表达基因"),
  di("黑色素瘤")
)
# M: Melanoma 黑色素瘤

```

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}

## GSE 数据搜索 (SKCM)

`r snap(gds.skcm, 0:3)`

```{r}
gds.skcm <- job_gds(c("Melanoma", "survival"), 30:1000)
#' @meth {get_meth(gds.skcm)}
gds.skcm@object$gdsType
gds.skcm <- step1(gds.skcm, grpl(gdsType, "^Expression[^;]*sequencing$|Expression profiling by array"))
vis(gds.skcm)
gds.skcm <- step2(gds.skcm)
gds.skcm$res$metas
hasSurv <- c(
  43, 42, 41, 39, 38, 37, 35, 34, 29, 27, 23, 20, 17, 13, 6
)
active(gds.skcm, which = hasSurv)
```

## Survival 生存分析 (GSE19234)

`r snap(surv.GSE19234, 0:3)`

`r ref("GSE19234-survival-curve-of-CAP2")` 
`r ref("GSE19234-time-ROC")` 

```{r}
geo.GSE19234 <- job_geo("GSE19234")
geo.GSE19234 <- step1(geo.GSE19234)
metadata.GSE19234 <- geo.GSE19234$guess
metadata.GSE19234 <- dplyr::mutate(
  metadata.GSE19234, 
  sample = rownames,
  vital_status = ifelse(staus.dead.or.alive.ch1 == "0", "Alive", "Dead"),
  group = vital_status,
  days_to_last_follow_up = as.integer(days.since.initial.diagnosis.ch1), .before = 1
)
metadata.GSE19234

lm.GSE19234 <- asjob_limma(geo.GSE19234, metadata.GSE19234)
lm.GSE19234 <- step1(lm.GSE19234)
filter(lm.GSE19234@object$genes, hgnc_symbol == "CAP2")

lm.GSE19234@object$counts
surv.GSE19234 <- asjob_survival(lm.GSE19234, "CAP2", use = "hgnc_symbol")
#' @meth {get_meth(surv.GSE19234)}
surv.GSE19234 <- step1(surv.GSE19234)
surv.GSE19234@plots$step1$p.surv$CAP2
surv.GSE19234@plots$step1$p.roc$CAP2
surv.GSE19234@tables$step1$t.SurvivalPValue
```

```{r eval = T, echo = F, results = "asis"}
#| GSE19234-survival-curve-of-CAP2
autor(surv.GSE19234@plots$step1$p.surv$CAP2)
```

```{r eval = T, echo = F, results = "asis"}
#| GSE19234-time-ROC
autor(surv.GSE19234@plots$step1$p.roc$CAP2)
```

## GSE 数据搜索 (SKCM_HEALTHY)

`r snap(gds.skcm_healthy, 0:3)`

```{r}
gds.skcm_healthy <- job_gds(c("Melanoma", "healthy"), 5:400)
#' @meth {get_meth(gds.skcm_healthy)}
vis(gds.skcm_healthy)
gds.skcm_healthy <- step1( gds.skcm_healthy, grpl(gdsType, "^Expression profiling by array$") )
gds.skcm_healthy <- step2(gds.skcm_healthy)
gds.skcm_healthy$res$metas
active(gds.skcm_healthy, which = 22:29)
which(gds.skcm_healthy@object$GSE == "")
gds.skcm_healthy$res$metas[[6]]
```

## GEO 数据获取 (GSE6887)

```{r}
geo.GSE6887 <- job_geo("GSE6887")
geo.GSE6887 <- step1(geo.GSE6887)
metadata.GSE6887 <- geo.GSE6887$guess
metadata.GSE6887 <- dplyr::mutate(
  metadata.GSE6887, sample = rownames,
  group = gs(title, "_[^_]+$", ""), .before = 1
)
metadata.GSE6887
```

## Limma 差异分析 (GSE6887)

```{r}
lm.GSE6887 <- asjob_limma(geo.GSE6887, metadata.GSE6887, normed = TRUE)
lm.GSE6887 <- step1(lm.GSE6887)
lm.GSE6887@params$genes
lm.GSE6887 <- step2(
  lm.GSE6887,
  B_cell_pool_melanoma - B_cell_pool_healthy,
  CD4_T_cell_pool_melanoma - CD4_T_cell_pool_healthy,
  CD8_T_cell_pool_melanoma - CD8_T_cell_pool_healthy,
  NK_cell_pool_melanoma - NK_cell_pool_healthy,
  use = "P", cut.fc = .3
)
lapply(lm.GSE6887@tables$step2$tops, dplyr::filter, grpl(GENE_SYMBOL, "CAP2"))

dplyr::filter(
  lm.GSE6887@tables$step2$tops$`B_cell_pool_melanoma - B_cell_pool_healthy`, grpl(GENE_SYMBOL, "CAP2")
)
```

# 总结 {#conclusion}

