---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(12), coef = NA)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

- 做药方-草药-单体-靶点图，着重显示单体-木兰花碱（magnoflorine）和靶点OPRM1。
- 木兰花碱与 OPRM1 的分子对接。

药理学结果见 Fig. \@ref(fig:Herbs-compounds-and-targets-Network)、

分子对接见 (亲和度为正值，对接不成功) Fig. \@ref(fig:magnoflorine-combining-with-OPRM1) 

# 材料和方法 {#methods}

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## `r odb("analysis")`

### 成分

```{r}
herbs <- c("知母", "黄柏", "熟地黄", "山茱萸", "牡丹皮", "山药", "泽泻", "柴胡", "当归", "白芍", "白术", "茯苓", "甘草", "薄荷")
hb <- job_herb(herbs)
hb@params$herbs_info <- dplyr::slice(hb@params$herbs_info, -5, -9)
hb@params$herbs_info <- dplyr::distinct(hb@params$herbs_info, Herb_cn_name, .keep_all = T)
hb <- step1(hb)
hb <- step2(hb, 100)
hb@step <- 2L
hb <- step3(hb, HLs = c("magnoflorine", "OPRM1"))
hb@params$easyRead
clear(hb)
```

```{r eval = T, echo = F, results = "asis"}
#| Herbs-information
autor(hb@params$herbs_info)
```

```{r eval = T, echo = F, results = "asis"}
#| Components-of-Herbs
autor(hb@tables$step1$herbs_compounds, key = "Ingredient.name")
```

```{r eval = T, echo = F, results = "asis"}
#| intersection-of-all-compounds
autor(wrap(hb@plots$step3$p.herbs_compounds, 12))
```

### 成分靶点

```{r eval = T, echo = F, results = "asis"}
#| tables-of-Herbs-compounds-and-targets
autor(hb@params$easyRead)
```

```{r eval = T, echo = F, results = "asis"}
#| Herbs-compounds-and-targets-Network
autor(hb@plots$step3$p.pharm)
```

## 分子对接

结合效果不佳 (Affinity 应为负值为佳) 

```{r}
cpd.mag <- dplyr::filter(hb@object$component, Ingredient_name == "magnoflorine")
cid <- cpd.mag$PubChem_id
vina <- job_vina(cid, "OPRM1")
vina <- step1(vina, NULL, pdbs = c("OPRM1" = "6DDE"))
vina <- step2(vina)
vina <- step3(vina)
vina <- step4(vina)
vina <- step5(vina, cpd.mag, "PubChem_id")
vina <- step6(vina)
vina <- step7(vina)
# 1.264
autosv(wrap(vina@plots$step5$p.res_vina, 8, 1.5), "Overall-combining-Affinity")
```

```{r eval = T, echo = F, results = "asis"}
#| Overall-combining-Affinity
autor("./Figure+Table/Overall-combining-Affinity.pdf")
```

以下为对接结果示意图 (没有成功，因此没有显示化合物 magnoflorine) 

```{r eval = T, echo = F, results = "asis"}
#| magnoflorine-combining-with-OPRM1
autor("./figs/73337_into_6dde.png")
```

```{r}
save_small(100)
load("./small.rdata")
```
