---
title: 
bibliography: '`r system.file("extdata", "library.bib", package = "utils.tool")`'
csl: '`r system.file("extdata", "nature.csl", package = "utils.tool")`'
reference-section-title: "Reference"
link-citations: true
output:
  bookdown::pdf_document2:
    # pandoc_args: [
      # "--filter", "pandoc-fignos",
      # "--filter", "pandoc-tablenos"
    # ]
    keep_tex: true
    keep_md: true
    toc: false
    # toc_depth: 4
    latex_engine: xelatex
header-includes:
  \usepackage{caption}
  \captionsetup{font={footnotesize},width=6in}
  \renewcommand{\dblfloatpagefraction}{.9}
  \makeatletter
  \renewenvironment{figure}
  {\def\@captype{figure}}
  \makeatother
  \@ifundefined{Shaded}{\newenvironment{Shaded}}
  \@ifundefined{snugshade}{\newenvironment{snugshade}}
  \renewenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
  \definecolor{shadecolor}{RGB}{230,230,230}
  \usepackage{xeCJK}
  \usepackage{setspace}
  \setstretch{1.3} 
  \usepackage{tcolorbox}
  \setcounter{secnumdepth}{4}
  \setcounter{tocdepth}{4}
  \usepackage{wallpaper}
  \usepackage[absolute]{textpos}
  \tcbuselibrary{breakable}
  \renewenvironment{Shaded}
  {\begin{tcolorbox}[colback = gray!10, colframe = gray!40, width = 16cm,
    arc = 1mm, auto outer arc, title = {R input}]}
  {\end{tcolorbox}}
  \usepackage{titlesec}
  \titleformat{\paragraph}
  {\fontsize{10pt}{0pt}\bfseries} {\arabic{section}.\arabic{subsection}.\arabic{subsubsection}.\arabic{paragraph}} {1em} {} []

---


```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(3), eval = ic(0, 1, 2, 0, 0))

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 数据来源

### 结肠炎数据

#### TargetedSuppreFederi2022 结肠炎

```{r eval = T, echo = F, results = "asis"}
#| TargetedSuppreFederi2022-data
autor(pb.uc_targ)
```

```{r}
file.copy("~/Downloads/mmc2 (1).xlsx", "./material/TargetedSuppreFederi2022_s2.xlsx", T)

pb.uc_targ <- fxlsx2(ref("./material/TargetedSuppreFederi2022_s2.xlsx"), pattern = "^Corrected", bind = F)
fun_format <- function(data) {
  group <- grpf(colnames(data)[-1], "^[^X]")
  group <- c("", rep(group, each = 2))
  colnames <- gs(paste0(unlist(data[1, ]), "_", group), "_$", "")
  data <- data[-1, ]
  colnames(data) <- colnames
  data <- dplyr::mutate(data, dplyr::across(dplyr::matches("_"), as.double))
  data <- dplyr::select(data, 1, dplyr::ends_with("_UC.vs.Ctrl"))
  data <- dplyr::filter(data, padj_UC.vs.Ctrl < .05)
  data
}
pb.uc_targ <- lapply(pb.uc_targ, fun_format)
pb.uc_targ

fun_upset <- function(lst) {
  lst.up <- lapply(lst, function(x) dplyr::filter(x, log2FoldChange_UC.vs.Ctrl > 0))
  lst.down <- lapply(lst, function(x) dplyr::filter(x, log2FoldChange_UC.vs.Ctrl < 0))
  fun <- function(lst) {
    new_upset(lst = lapply(lst, function(x) x$Species))
  }
  lst <- list(lst.up = fun(lst.up), lst.down = fun(lst.down))
  alls <- unique(unlist(lapply(lst, function(x) x$ins)))
  c(lst, namel(alls))
}

upset.uc_targ <- fun_upset(pb.uc_targ)
upset.uc_targ$lst.up
upset.uc_targ$lst.down
upset.uc_targ$lst.down$ins

```

#### DepressionAndYuan2021 结肠炎

```{r eval = T, echo = F, results = "asis"}
#| DepressionAndYuan2021-data
autor(pb.uc_dep)
```

```{r}
file.copy("~/Downloads/KGMI_A_1987779_SM8304.zip", "./material")
unzip("./material/KGMI_A_1987779_SM8304.zip", exdir = "./material/DepressionAndYuan2021")
```

```{r}
browseURL("./material/DepressionAndYuan2021/Supplementary information/Supplementary table.xlsx")

pb.uc_dep <- fxlsx(ref("./material/DepressionAndYuan2021/Supplementary information/Supplementary table.xlsx"),
  sheet = 3, startRow = 2)
pb.uc_dep
```

#### TransplantationSinha2022 结肠炎

```{r eval = T, echo = F, results = "asis"}
#| TransplantationSinha2022-data
autor(pb.uc_trans)
```

```{r}
file.copy("~/Downloads/40168_2022_1275_MOESM3_ESM.xlsx", "./material/TransplantationSinha2022_s3.xlsx")
browseURL("./material/TransplantationSinha2022_s3.xlsx")
pb.uc_trans <- fxlsx(ref("./material/TransplantationSinha2022_s3.xlsx"), startRow = 3)
pb.uc_trans <- dplyr::filter(pb.uc_trans, detected_0.9)
pb.uc_trans
strx(pb.uc_trans$Genus, "^[a-zA-Z]+") %in% strx(upset.uc_targ$alls, "^[a-zA-Z]+")

```

### 结肠癌数据

#### AnIntegratedTRoelan2023 结肠癌

```{r eval = T, echo = F, results = "asis"}
#| AnIntegratedTRoelan2023-data
autor(pb.ca_anin)
```

```{r}
file.copy("~/Downloads/41591_2023_2324_MOESM3_ESM.xlsx", "./material/AnIntegratedTRoelan2023_s2-11.xlsx")

pb.ca_anin <- fxlsx2(ref("./material/AnIntegratedTRoelan2023_s2-11.xlsx"), pattern = "Supplementary Table 5", startRow = 2)
pb.ca_anin <- dplyr::filter(pb.ca_anin, FDR < .05)
pb.ca_anin

```

#### LocationAndCoSambru2023 结肠癌

```{r eval = T, echo = F, results = "asis"}
#| LocationAndCoSambru2023-data
autor(pb.ca_loca)
```

```{r}
file.copy("~/Downloads/13073_2023_1180_MOESM4_ESM.txt", "./material/LocationAndCoSambru2023_s4.txt")
pb.ca_loca <- ftibble(ref("./material/LocationAndCoSambru2023_s4.txt"))
pb.ca_loca
```

## 微生物注释

```{r}
query_class(rep("Coprococcus", 2))
```


