---
---

```{r include = F, eval = F}
deparse_mail()
info <- items(belong = odate(3), eval = ic(1, 1, 0, 0, 0))
show.ic(info)

order_publish()
idname <- order_packaging()
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover(info$title)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

```{r}
dic(di("差异表达基因", "Differential Expressed Genes", "DEGs"))

```

为了鉴定 VASH2 被 PRMT5 甲基化的精氨酸残基 (methylarginine)，使用甲基化预测工具包括 PRmePred 和 GPS-MSP 分析 VASH2 的蛋白序列

- MusiteDeep <https://www.musite.net> <https://github.com/duolinwang/MusiteDeep_web>
- PRmePred <http://bioinfo.icgeb.res.in/PRmePRed/>
- GPS-MSP <https://msp.biocuckoo.org/>

protein post-translational modification site (PTM)

# 前言 {#introduction}

# 材料和方法 {#methods}

## 材料

```{r eval = T, echo = F, results = "asis"}
auto_material()
```

## 方法

```{r eval = T, echo = F, results = "asis"}
auto_method()
```

# 分析结果 {#results}

# 结论 {#dis}

# 附：分析流程 {#workflow}

## 获取蛋白序列

## 预测位点

### MusiteDeep

```{r eval = T, echo = F, results = "asis"}
#| Prediction-PTM-of-Methylarginine
autor(ms@tables$step2$t.data)
```

```{r eval = T, echo = F, results = "asis"}
#| High-score-prediction-PTM-of-Methylarginine
autor(ms@tables$step2$t.cutoff)
```

```{r}
ms <- job_musite("VASH2")
ms <- step1(ms)

ms@step <- 1L
ms <- step2(ms, "Methylarginine")
ms@tables$step2$t.data

```


