---
---

```{r include = F, eval = F}
info <- items(start = td("2025-02-10"), end = td("2025-02-10"), finish = td("2025-02-10"),
  id = "BSXL240708", client = "宛迎春", inst = "",
  type = "生信分析",
  title = "卵巢癌耐药性",
  save = ".items_analysis.rds"
)
show.ic(info)

order_publish.bosai("analysis.Rmd", "analysis_out.Rmd")
idname <- formatName.bosai("./analysis_out.docx")
order_packaging("./analysis_out.docx", idname = idname, external_file = NULL)
```

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_cover.bosai(info)
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 分析流程 {#abstract}

```{r}
dic(di("差异表达基因"),
  di("")
)

```

- 不同RUNX2水平癌症患者总生存期的荟萃分析（根据文献情况及分析结果选择是否保留）。
  (预期：RUNX2高表达预后不好)
- 基于ENCORI平台的卵巢癌和癌旁组织中RUNX2水平的比较
- 显示TMA（组织微阵列）中RUNX2蛋白的IHC评分的箱形图。
- 不同RUNX2水平的卵巢癌患者的总生存期。
- GEO数据集验证RUNX2 mRNA在耐药细胞系中的表达

# 材料和方法 {#introduction}

```{r eval = T, echo = F, results = "asis"}
collate_details("meth")
```

# 分析结果 {#workflow}



# 总结 {#conclusion}

