---
---

```{r include = F}
#| setup
if (!requireNamespace("utils.tool"))
  devtools::load_all("~/utils.tool/")
autor_preset()
## the package are available at <https://github.com/shaman-yellow/utils.tool>
## if you want to run codes of this Rmarkdown,
## please install the package `utils.tool` and other related packages (run
## install.R)
options(savedir = list(figs = "Figure+Table", tabs = "Figure+Table"))
```

```{r eval = T, echo = F, results = "asis"}
set_index()
```

# 摘要 {#abstract}

# 研究设计流程图 {#route}

```{r}
#| route
route <- as_network(
  list("RNA_seq_data:Preprocess",
    ), "tree"
)
p.route <- flowChart(route, 1.1, 1)
```

```{r, eval = T, echo = F, fig.width = 10, fig.height = 7, fig.cap = NULL}
p.route
```

# 材料和方法 {#methods}

# 分析结果 {#results}

```{r}
new_package.fromFiles("~/touchPDB",
  c("workflow_zzz_protein_db.R"),
  path = "~/utils.tool/R/", depends = NULL)
file.copy(c("~/utils.tool/R/a.R", "~/utils.tool/R/workflow_00.R"), "~/touchPDB/R", T)
roxygen2::roxygenize("~/touchPDB")

devtools::build("~/touchPDB", ".")
```

## 使用示例

```{r, echo = T}
syms <- c("ERBB4", "Pik3r1", "AHR", "TP53")
pd <- new_pdb()
pd <- via_symbol(pd, syms)
anno(pd, syms)
```

# 结论 {#dis}
